# -*- coding: utf-8 -*-
#
# GPL License and Copyright Notice ============================================
#  This file is part of Wrye Bash.
#
#  Wrye Bash is free software: you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation, either version 3
#  of the License, or (at your option) any later version.
#
#  Wrye Bash is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Wrye Bash.  If not, see <https://www.gnu.org/licenses/>.
#
#  Wrye Bash copyright (C) 2005-2009 Wrye, 2010-2020 Wrye Bash Team
#  https://github.com/wrye-bash
#
# =============================================================================

#--Game ESM/ESP/BSA files
#  These filenames need to be in lowercase,
bethDataFiles = {
    #--Vanilla
    u'skyrim.esm',
    u'update.esm',
    u'update.bsa',
    u'dawnguard.esm',
    u'dawnguard.bsa',
    u'hearthfires.bsa',
    u'hearthfires.esm',
    u'dragonborn.esm',
    u'dragonborn.bsa',
    u'skyrim - animations.bsa',
    u'skyrim - interface.bsa',
    u'skyrim - meshes.bsa',
    u'skyrim - misc.bsa',
    u'skyrim - shaders.bsa',
    u'skyrim - sounds.bsa',
    u'skyrim - textures.bsa',
    u'skyrim - voices.bsa',
    u'skyrim - voicesextra.bsa',
    u'highrestexturepack01.esp',
    u'highrestexturepack02.esp',
    u'highrestexturepack03.esp',
    u'highrestexturepack01.bsa',
    u'highrestexturepack02.bsa',
    u'highrestexturepack03.bsa',
}

# Function Info ---------------------------------------------------------------
# 0: no param; 1: int param; 2: formid param; 3: float param
# Third parameter is always sint32, so no need to specify here
condition_function_data = {
    0:    (u'GetWantBlocking', 0, 0),
    1:    (u'GetDistance', 2, 0),
    5:    (u'GetLocked', 0, 0),
    6:    (u'GetPos', 0, 0),
    8:    (u'GetAngle', 0, 0),
    10:   (u'GetStartingPos', 0, 0),
    11:   (u'GetStartingAngle', 0, 0),
    12:   (u'GetSecondsPassed', 0, 0),
    14:   (u'GetActorValue', 2, 0),
    18:   (u'GetCurrentTime', 0, 0),
    24:   (u'GetScale', 0, 0),
    25:   (u'IsMoving', 0, 0),
    26:   (u'IsTurning', 0, 0),
    27:   (u'GetLineOfSight', 2, 0),
    32:   (u'GetInSameCell', 2, 0),
    35:   (u'GetDisabled', 0, 0),
    36:   (u'MenuMode', 1, 0),
    39:   (u'GetDisease', 0, 0),
    41:   (u'GetClothingValue', 0, 0),
    42:   (u'SameFaction', 2, 0),
    43:   (u'SameRace', 2, 0),
    44:   (u'SameSex', 2, 0),
    45:   (u'GetDetected', 2, 0),
    46:   (u'GetDead', 0, 0),
    47:   (u'GetItemCount', 2, 0),
    48:   (u'GetGold', 0, 0),
    49:   (u'GetSleeping', 0, 0),
    50:   (u'GetTalkedToPC', 0, 0),
    53:   (u'GetScriptVariable', 2, 0),
    56:   (u'GetQuestRunning', 2, 0),
    58:   (u'GetStage', 2, 0),
    59:   (u'GetStageDone', 2, 1),
    60:   (u'GetFactionRankDifference', 2, 2),
    61:   (u'GetAlarmed', 0, 0),
    62:   (u'IsRaining', 0, 0),
    63:   (u'GetAttacked', 0, 0),
    64:   (u'GetIsCreature', 0, 0),
    65:   (u'GetLockLevel', 0, 0),
    66:   (u'GetShouldAttack', 2, 0),
    67:   (u'GetInCell', 2, 0),
    68:   (u'GetIsClass', 2, 0),
    69:   (u'GetIsRace', 2, 0),
    70:   (u'GetIsSex', 1, 0),
    71:   (u'GetInFaction', 2, 0),
    72:   (u'GetIsID', 2, 0),
    73:   (u'GetFactionRank', 2, 0),
    74:   (u'GetGlobalValue', 2, 0),
    75:   (u'IsSnowing', 0, 0),
    77:   (u'GetRandomPercent', 0, 0),
    79:   (u'GetQuestVariable', 2, 0),
    80:   (u'GetLevel', 0, 0),
    81:   (u'IsRotating', 0, 0),
    84:   (u'GetDeadCount', 2, 0),
    91:   (u'GetIsAlerted', 0, 0),
    98:   (u'GetPlayerControlsDisabled', 1, 1),
    99:   (u'GetHeadingAngle', 2, 0),
    101:  (u'IsWeaponMagicOut', 0, 0),
    102:  (u'IsTorchOut', 0, 0),
    103:  (u'IsShieldOut', 0, 0),
    106:  (u'IsFacingUp', 0, 0),
    107:  (u'GetKnockedState', 0, 0),
    108:  (u'GetWeaponAnimType', 0, 0),
    109:  (u'IsWeaponSkillType', 2, 0),
    110:  (u'GetCurrentAIPackage', 0, 0),
    111:  (u'IsWaiting', 0, 0),
    112:  (u'IsIdlePlaying', 0, 0),
    116:  (u'IsIntimidatedbyPlayer', 0, 0),
    117:  (u'IsPlayerInRegion', 0, 0),
    118:  (u'GetActorAggroRadiusViolated', 0, 0),
    122:  (u'GetCrime', 2, 1),
    123:  (u'IsGreetingPlayer', 0, 0),
    125:  (u'IsGuard', 0, 0),
    127:  (u'HasBeenEaten', 0, 0),
    128:  (u'GetStaminaPercentage', 0, 0),
    129:  (u'GetPCIsClass', 2, 0),
    130:  (u'GetPCIsRace', 2, 0),
    131:  (u'GetPCIsSex', 1, 0),
    132:  (u'GetPCInFaction', 2, 0),
    133:  (u'SameFactionAsPC', 0, 0),
    134:  (u'SameRaceAsPC', 0, 0),
    135:  (u'SameSexAsPC', 0, 0),
    136:  (u'GetIsReference', 2, 0),
    141:  (u'IsTalking', 0, 0),
    142:  (u'GetWalkSpeed', 0, 0),
    143:  (u'GetCurrentAIProcedure', 0, 0),
    144:  (u'GetTrespassWarningLevel', 0, 0),
    145:  (u'IsTrespassing', 0, 0),
    146:  (u'IsInMyOwnedCell', 0, 0),
    147:  (u'GetWindSpeed', 0, 0),
    148:  (u'GetCurrentWeatherPercent', 0, 0),
    149:  (u'GetIsCurrentWeather', 2, 0),
    150:  (u'IsContinuingPackagePCNear', 0, 0),
    152:  (u'GetIsCrimeFaction', 2, 0),
    153:  (u'CanHaveFlames', 0, 0),
    154:  (u'HasFlames', 0, 0),
    157:  (u'GetOpenState', 0, 0),
    159:  (u'GetSitting', 0, 0),
    161:  (u'GetIsCurrentPackage', 2, 0),
    162:  (u'IsCurrentFurnitureRef', 2, 0),
    163:  (u'IsCurrentFurnitureObj', 2, 0),
    170:  (u'GetDayOfWeek', 0, 0),
    172:  (u'GetTalkedToPCParam', 2, 0),
    175:  (u'IsPCSleeping', 0, 0),
    176:  (u'IsPCAMurderer', 0, 0),
    180:  (u'HasSameEditorLocAsRef', 2, 2),
    181:  (u'HasSameEditorLocAsRefAlias', 1, 2),
    182:  (u'GetEquipped', 2, 0),
    185:  (u'IsSwimming', 0, 0),
    190:  (u'GetAmountSoldStolen', 0, 0),
    192:  (u'GetIgnoreCrime', 0, 0),
    193:  (u'GetPCExpelled', 2, 0),
    195:  (u'GetPCFactionMurder', 2, 0),
    197:  (u'GetPCEnemyofFaction', 2, 0),
    199:  (u'GetPCFactionAttack', 2, 0),
    203:  (u'GetDestroyed', 0, 0),
    214:  (u'HasMagicEffect', 2, 0),
    215:  (u'GetDefaultOpen', 0, 0),
    219:  (u'GetAnimAction', 0, 0),
    223:  (u'IsSpellTarget', 2, 0),
    224:  (u'GetVATSMode', 0, 0),
    225:  (u'GetPersuasionNumber', 0, 0),
    226:  (u'GetVampireFeed', 0, 0),
    227:  (u'GetCannibal', 0, 0),
    228:  (u'GetIsClassDefault', 2, 0),
    229:  (u'GetClassDefaultMatch', 0, 0),
    230:  (u'GetInCellParam', 2, 2),
    235:  (u'GetVatsTargetHeight', 0, 0),
    237:  (u'GetIsGhost', 0, 0),
    242:  (u'GetUnconscious', 0, 0),
    244:  (u'GetRestrained', 0, 0),
    246:  (u'GetIsUsedItem', 2, 0),
    247:  (u'GetIsUsedItemType', 2, 0),
    248:  (u'IsScenePlaying', 2, 0),
    249:  (u'IsInDialogueWithPlayer', 0, 0),
    250:  (u'GetLocationCleared', 2, 0),
    254:  (u'GetIsPlayableRace', 0, 0),
    255:  (u'GetOffersServicesNow', 0, 0),
    258:  (u'HasAssociationType', 2, 2),
    259:  (u'HasFamilyRelationship', 2, 0),
    261:  (u'HasParentRelationship', 2, 0),
    262:  (u'IsWarningAbout', 2, 0),
    263:  (u'IsWeaponOut', 0, 0),
    264:  (u'HasSpell', 2, 0),
    265:  (u'IsTimePassing', 0, 0),
    266:  (u'IsPleasant', 0, 0),
    267:  (u'IsCloudy', 0, 0),
    274:  (u'IsSmallBump', 0, 0),
    277:  (u'GetBaseActorValue', 2, 0),
    278:  (u'IsOwner', 2, 0),
    280:  (u'IsCellOwner', 2, 2),
    282:  (u'IsHorseStolen', 0, 0),
    285:  (u'IsLeftUp', 0, 0),
    286:  (u'IsSneaking', 0, 0),
    287:  (u'IsRunning', 0, 0),
    288:  (u'GetFriendHit', 0, 0),
    289:  (u'IsInCombat', 1, 0),
    300:  (u'IsInInterior', 0, 0),
    304:  (u'IsWaterObject', 0, 0),
    305:  (u'GetPlayerAction', 0, 0),
    306:  (u'IsActorUsingATorch', 0, 0),
    309:  (u'IsXBox', 0, 0),
    310:  (u'GetInWorldspace', 2, 0),
    312:  (u'GetPCMiscStat', 0, 0),
    313:  (u'GetPairedAnimation', 0, 0),
    314:  (u'IsActorAVictim', 0, 0),
    315:  (u'GetTotalPersuasionNumber', 0, 0),
    318:  (u'GetIdleDoneOnce', 0, 0),
    320:  (u'GetNoRumors', 0, 0),
    323:  (u'GetCombatState', 0, 0),
    325:  (u'GetWithinPackageLocation', 0, 0),
    327:  (u'IsRidingMount', 0, 0),
    329:  (u'IsFleeing', 0, 0),
    332:  (u'IsInDangerousWater', 0, 0),
    338:  (u'GetIgnoreFriendlyHits', 0, 0),
    339:  (u'IsPlayersLastRiddenMount', 0, 0),
    353:  (u'IsActor', 0, 0),
    354:  (u'IsEssential', 0, 0),
    358:  (u'IsPlayerMovingIntoNewSpace', 0, 0),
    359:  (u'GetInCurrentLoc', 2, 0),
    360:  (u'GetInCurrentLocAlias', 1, 0),
    361:  (u'GetTimeDead', 0, 0),
    362:  (u'HasLinkedRef', 2, 0),
    365:  (u'IsChild', 0, 0),
    366:  (u'GetStolenItemValueNoCrime', 2, 0),
    367:  (u'GetLastPlayerAction', 0, 0),
    368:  (u'IsPlayerActionActive', 1, 0),
    370:  (u'IsTalkingActivatorActor', 2, 0),
    372:  (u'IsInList', 2, 0),
    373:  (u'GetStolenItemValue', 2, 0),
    375:  (u'GetCrimeGoldViolent', 2, 0),
    376:  (u'GetCrimeGoldNonviolent', 2, 0),
    378:  (u'HasShout', 2, 0),
    381:  (u'GetHasNote', 2, 0),
    390:  (u'GetHitLocation', 0, 0),
    391:  (u'IsPC1stPerson', 0, 0),
    396:  (u'GetCauseofDeath', 0, 0),
    397:  (u'IsLimbGone', 1, 0),
    398:  (u'IsWeaponInList', 2, 0),
    402:  (u'IsBribedbyPlayer', 0, 0),
    403:  (u'GetRelationshipRank', 2, 0),
    # We set the second to 'unused' here to receive it as 4 bytes, which we
    # then handle inside MelCtdaFo3.
    407:  (u'GetVATSValue', 1, 0),
    408:  (u'IsKiller', 2, 0),
    409:  (u'IsKillerObject', 2, 0),
    410:  (u'GetFactionCombatReaction', 2, 2),
    414:  (u'Exists', 2, 0),
    415:  (u'GetGroupMemberCount', 0, 0),
    416:  (u'GetGroupTargetCount', 0, 0),
    426:  (u'GetIsVoiceType', 2, 0),
    427:  (u'GetPlantedExplosive', 0, 0),
    429:  (u'IsScenePackageRunning', 0, 0),
    430:  (u'GetHealthPercentage', 0, 0),
    432:  (u'GetIsObjectType', 2, 0),
    434:  (u'GetDialogueEmotion', 0, 0),
    435:  (u'GetDialogueEmotionValue', 0, 0),
    437:  (u'GetIsCreatureType', 1, 0),
    444:  (u'GetInCurrentLocFormList', 2, 0),
    445:  (u'GetInZone', 2, 0),
    446:  (u'GetVelocity', 0, 0),
    447:  (u'GetGraphVariableFloat', 0, 0),
    448:  (u'HasPerk', 2, 0),
    449:  (u'GetFactionRelation', 2, 0),
    450:  (u'IsLastIdlePlayed', 2, 0),
    453:  (u'GetPlayerTeammate', 0, 0),
    454:  (u'GetPlayerTeammateCount', 0, 0),
    458:  (u'GetActorCrimePlayerEnemy', 0, 0),
    459:  (u'GetCrimeGold', 2, 0),
    463:  (u'IsPlayerGrabbedRef', 2, 0),
    465:  (u'GetKeywordItemCount', 2, 0),
    470:  (u'GetDestructionStage', 0, 0),
    473:  (u'GetIsAlignment', 2, 0),
    476:  (u'IsProtected', 0, 0),
    477:  (u'GetThreatRatio', 2, 0),
    479:  (u'GetIsUsedItemEquipType', 2, 0),
    487:  (u'IsCarryable', 0, 0),
    488:  (u'GetConcussed', 0, 0),
    491:  (u'GetMapMarkerVisible', 0, 0),
    493:  (u'PlayerKnows', 0, 0),
    494:  (u'GetPermanentActorValue', 2, 0),
    495:  (u'GetKillingBlowLimb', 0, 0),
    497:  (u'CanPayCrimeGold', 2, 0),
    499:  (u'GetDaysInJail', 0, 0),
    500:  (u'EPAlchemyGetMakingPoison', 0, 0),
    501:  (u'EPAlchemyEffectHasKeyword', 2, 0),
    503:  (u'GetAllowWorldInteractions', 0, 0),
    508:  (u'GetLastHitCritical', 0, 0),
    513:  (u'IsCombatTarget', 2, 0),
    515:  (u'GetVATSRightAreaFree', 2, 0),
    516:  (u'GetVATSLeftAreaFree', 2, 0),
    517:  (u'GetVATSBackAreaFree', 2, 0),
    518:  (u'GetVATSFrontAreaFree', 2, 0),
    519:  (u'GetIsLockBroken', 0, 0),
    520:  (u'IsPS3', 0, 0),
    521:  (u'IsWin32', 0, 0),
    522:  (u'GetVATSRightTargetVisible', 2, 0),
    523:  (u'GetVATSLeftTargetVisible', 2, 0),
    524:  (u'GetVATSBackTargetVisible', 2, 0),
    525:  (u'GetVATSFrontTargetVisible', 2, 0),
    528:  (u'IsInCriticalStage', 2, 0),
    530:  (u'GetXPForNextLevel', 0, 0),
    533:  (u'GetInfamy', 2, 0),
    534:  (u'GetInfamyViolent', 2, 0),
    535:  (u'GetInfamyNonViolent', 2, 0),
    543:  (u'GetQuestCompleted', 2, 0),
    547:  (u'IsGoreDisabled', 0, 0),
    550:  (u'IsSceneActionComplete', 2, 1),
    552:  (u'GetSpellUsageNum', 2, 0),
    554:  (u'GetActorsInHigh', 0, 0),
    555:  (u'HasLoaded3D', 0, 0),
    560:  (u'HasKeyword', 2, 0),
    561:  (u'HasRefType', 2, 0),
    562:  (u'LocationHasKeyword', 2, 0),
    563:  (u'LocationHasRefType', 2, 0),
    565:  (u'GetIsEditorLocation', 2, 0),
    566:  (u'GetIsAliasRef', 1, 0),
    567:  (u'GetIsEditorLocAlias', 1, 0),
    568:  (u'IsSprinting', 0, 0),
    569:  (u'IsBlocking', 0, 0),
    570:  (u'HasEquippedSpell', 2, 0),
    571:  (u'GetCurrentCastingType', 2, 0),
    572:  (u'GetCurrentDeliveryType', 2, 0),
    574:  (u'GetAttackState', 0, 0),
    576:  (u'GetEventData', 0, 2),
    577:  (u'IsCloserToAThanB', 2, 2),
    579:  (u'GetEquippedShout', 2, 0),
    580:  (u'IsBleedingOut', 0, 0),
    584:  (u'GetRelativeAngle', 2, 0),
    589:  (u'GetMovementDirection', 0, 0),
    590:  (u'IsInScene', 0, 0),
    591:  (u'GetRefTypeDeadCount', 2, 2),
    592:  (u'GetRefTypeAliveCount', 2, 2),
    594:  (u'GetIsFlying', 0, 0),
    595:  (u'IsCurrentSpell', 2, 2),
    596:  (u'SpellHasKeyword', 2, 2),
    597:  (u'GetEquippedItemType', 2, 0),
    598:  (u'GetLocationAliasCleared', 1, 0),
    600:  (u'GetLocAliasRefTypeDeadCount', 1, 2),
    601:  (u'GetLocAliasRefTypeAliveCount', 1, 2),
    602:  (u'IsWardState', 0, 0),
    603:  (u'IsInSameCurrentLocAsRef', 2, 2),
    604:  (u'IsInSameCurrentLocAsRefAlias', 1, 2),
    605:  (u'LocAliasIsLocation', 1, 2),
    606:  (u'GetKeywordDataForLocation', 2, 2),
    608:  (u'GetKeywordDataForAlias', 1, 2),
    610:  (u'LocAliasHasKeyword', 1, 2),
    611:  (u'IsNullPackageData', 0, 0),
    612:  (u'GetNumericPackageData', 0, 0),
    613:  (u'IsFurnitureAnimType', 0, 0),
    614:  (u'IsFurnitureEntryType', 0, 0),
    615:  (u'GetHighestRelationshipRank', 0, 0),
    616:  (u'GetLowestRelationshipRank', 0, 0),
    617:  (u'HasAssociationTypeAny', 2, 0),
    618:  (u'HasFamilyRelationshipAny', 0, 0),
    619:  (u'GetPathingTargetOffset', 0, 0),
    620:  (u'GetPathingTargetAngleOffset', 0, 0),
    621:  (u'GetPathingTargetSpeed', 0, 0),
    622:  (u'GetPathingTargetSpeedAngle', 0, 0),
    623:  (u'GetMovementSpeed', 0, 0),
    624:  (u'GetInContainer', 2, 0),
    625:  (u'IsLocationLoaded', 2, 0),
    626:  (u'IsLocAliasLoaded', 1, 0),
    627:  (u'IsDualCasting', 0, 0),
    629:  (u'GetVMQuestVariable', 2, 0),
    630:  (u'GetVMScriptVariable', 2, 0),
    631:  (u'IsEnteringInteractionQuick', 0, 0),
    632:  (u'IsCasting', 0, 0),
    633:  (u'GetFlyingState', 0, 0),
    635:  (u'IsInFavorState', 0, 0),
    636:  (u'HasTwoHandedWeaponEquipped', 0, 0),
    637:  (u'IsExitingInstant', 0, 0),
    638:  (u'IsInFriendStatewithPlayer', 0, 0),
    639:  (u'GetWithinDistance', 2, 3),
    640:  (u'GetActorValuePercent', 2, 0),
    641:  (u'IsUnique', 0, 0),
    642:  (u'GetLastBumpDirection', 0, 0),
    644:  (u'IsInFurnitureState', 0, 0),
    645:  (u'GetIsInjured', 0, 0),
    646:  (u'GetIsCrashLandRequest', 0, 0),
    647:  (u'GetIsHastyLandRequest', 0, 0),
    650:  (u'IsLinkedTo', 2, 2),
    651:  (u'GetKeywordDataForCurrentLocation', 2, 0),
    652:  (u'GetInSharedCrimeFaction', 2, 0),
    654:  (u'GetBribeSuccess', 0, 0),
    655:  (u'GetIntimidateSuccess', 0, 0),
    656:  (u'GetArrestedState', 0, 0),
    657:  (u'GetArrestingActor', 0, 0),
    659:  (u'EPTemperingItemIsEnchanted', 0, 0),
    660:  (u'EPTemperingItemHasKeyword', 2, 0),
    664:  (u'GetReplacedItemType', 2, 0),
    672:  (u'IsAttacking', 0, 0),
    673:  (u'IsPowerAttacking', 0, 0),
    674:  (u'IsLastHostileActor', 0, 0),
    675:  (u'GetGraphVariableInt', 0, 0),
    676:  (u'GetCurrentShoutVariation', 0, 0),
    678:  (u'ShouldAttackKill', 2, 0),
    680:  (u'GetActivationHeight', 0, 0),
    681:  (u'EPModSkillUsage_IsAdvanceSkill', 2, 0),
    682:  (u'WornHasKeyword', 2, 0),
    683:  (u'GetPathingCurrentSpeed', 0, 0),
    684:  (u'GetPathingCurrentSpeedAngle', 0, 0),
    691:  (u'EPModSkillUsage_AdvanceObjectHasKeyword', 2, 0),
    692:  (u'EPModSkillUsage_IsAdvanceAction', 0, 0),
    693:  (u'EPMagic_SpellHasKeyword', 2, 0),
    694:  (u'GetNoBleedoutRecovery', 0, 0),
    696:  (u'EPMagic_SpellHasSkill', 2, 0),
    697:  (u'IsAttackType', 2, 0),
    698:  (u'IsAllowedToFly', 0, 0),
    699:  (u'HasMagicEffectKeyword', 2, 0),
    700:  (u'IsCommandedActor', 0, 0),
    701:  (u'IsStaggered', 0, 0),
    702:  (u'IsRecoiling', 0, 0),
    703:  (u'IsExitingInteractionQuick', 0, 0),
    704:  (u'IsPathing', 0, 0),
    705:  (u'GetShouldHelp', 2, 0),
    706:  (u'HasBoundWeaponEquipped', 2, 0),
    707:  (u'GetCombatTargetHasKeyword', 2, 0),
    709:  (u'GetCombatGroupMemberCount', 0, 0),
    710:  (u'IsIgnoringCombat', 0, 0),
    711:  (u'GetLightLevel', 0, 0),
    713:  (u'SpellHasCastingPerk', 2, 0),
    714:  (u'IsBeingRidden', 0, 0),
    715:  (u'IsUndead', 0, 0),
    716:  (u'GetRealHoursPassed', 0, 0),
    718:  (u'IsUnlockedDoor', 0, 0),
    719:  (u'IsHostileToActor', 2, 0),
    720:  (u'GetTargetHeight', 2, 0),
    721:  (u'IsPoison', 0, 0),
    722:  (u'WornApparelHasKeywordCount', 2, 0),
    723:  (u'GetItemHealthPercent', 0, 0),
    724:  (u'EffectWasDualCast', 0, 0),
    725:  (u'GetKnockStateEnum', 0, 0),
    726:  (u'DoesNotExist', 0, 0),
    730:  (u'IsOnFlyingMount', 0, 0),
    731:  (u'CanFlyHere', 0, 0),
    732:  (u'IsFlyingMountPatrolQueued', 0, 0),
    733:  (u'IsFlyingMountFastTravelling', 0, 0),
    734:  (u'IsOverEncumbered', 0, 0),
    735:  (u'GetActorWarmth', 0, 0),

    # extended by SKSE
    1024: (u'GetSKSEVersion', 0, 0),
    1025: (u'GetSKSEVersionMinor', 0, 0),
    1026: (u'GetSKSEVersionBeta', 0, 0),
    1027: (u'GetSKSERelease', 0, 0),
    1028: (u'ClearInvalidRegistrations', 0, 0),
}
getvatsvalue_index = 407

GlobalsTweaks = [
    (_(u'World: Timescale'),_(u'Timescale will be set to:'),
        u'timescale',
        (u'1',         1),
        (u'8',         8),
        (u'10',       10),
        (u'12',       12),
        (u'[20]',     20),
        (u'24',       24),
        (u'30',       30),
        (u'40',       40),
        (_(u'Custom'), 20),
        ),
    ]

GmstTweaks = [
    (_(u'Msg: Soul Captured'),
     _(u'Message upon capturing a soul in a Soul Gem.'),
       (u'sSoulCaptured',),
       (_(u'[None]'),         u' '),
       (u'.',                 u'.'),
       (_(u'Hmm...'), _(u'Hmm...')),
       (_(u'Custom'),      _(u' ')),
       ),
    (_(u'Actor: Strength Encumbrance Multiplier'),_(u"Actor's Strength X this = Actor's Encumbrance capacity."),
        (u'fActorStrengthEncumbranceMult',),
        (u'1',                 1.0),
        (u'3',                 3.0),
        (u'[5]',               5.0),
        (u'8',                 8.0),
        (u'10',               10.0),
        (u'20',               20.0),
        (_(u'Unlimited'), 999999.0),
        (_(u'Custom'),         5.0),
        ),
    (_(u'AI: Max Active Actors'),
     _(u'Maximum actors whose AI can be active. Must be higher than Combat: Max Actors'),
        (u'iAINumberActorsComplexScene',),
        (u'[20]',       20),
        (u'25',         25),
        (u'30',         30),
        (u'35',         35),
        (u'40',         40),
        (u'50',         50),
        (u'60',         60),
        (u'100',       100),
        (_(u'Custom'),  20),
        ),
    (_(u'Arrow: Recovery from Actor'),_(u'Chance that an arrow shot into an actor can be recovered.'),
        (u'iArrowInventoryChance',),
        (u'[33%]',     33),
        (u'50%',       50),
        (u'60%',       60),
        (u'70%',       70),
        (u'80%',       80),
        (u'90%',       90),
        (u'100%',     100),
        (_(u'Custom'), 33),
        ),
    (_(u'Arrow: Speed'),_(u'Speed of a full power arrow.'),
        (u'fArrowSpeedMult',),
        (u'[x 1.0]',                  1500.0),
        (u'x 1.2',                1500.0*1.2),
        (u'x 1.4',                1500.0*1.4),
        (u'x 1.6',                1500.0*1.6),
        (u'x 1.8',                1500.0*1.8),
        (u'x 2.0',                1500.0*2.0),
        (u'x 2.2',                1500.0*2.2),
        (u'x 2.4',                1500.0*2.4),
        (u'x 2.6',                1500.0*2.6),
        (u'x 2.8',                1500.0*2.8),
        (u'x 3.0',                1500.0*3.0),
        (_(u'Custom (base is 1500)'), 1500.0),
        ),
    (_(u'World: Cell Respawn Time'),
     _(u'Time before unvisited cells respawn. Longer times increase save game '
       u'size.'),
        (u'iHoursToRespawnCell',),
        (_(u'1 Day'),           24*1),
        (_(u'3 Days'),          24*3),
        (_(u'5 Days'),          24*5),
        (_(u'[10 Days]'),      24*10),
        (_(u'20 Days'),        24*20),
        (_(u'1 Month'),        24*30),
        (_(u'6 Months'),      24*182),
        (_(u'1 Year'),        24*365),
        (_(u'Custom (in hours)'), 240),
        ),
    (_(u'World: Cell Respawn Time (Cleared)'),
     _(u'Time before a cleared cell will respawn. Longer times increase save '
       u'game size.'),
        (u'iHoursToRespawnCellCleared',),
        (_(u'10 Days'),         24*10),
        (_(u'15 Days'),         24*15),
        (_(u'20 Days'),         24*20),
        (_(u'25 Days'),         24*25),
        (_(u'[30 Days]'),       24*30),
        (_(u'2 Months'),        24*60),
        (_(u'6 Months'),      24*180),
        (_(u'1 Year'),        24*365),
        (_(u'Custom (in hours)'), 720),
        ),
    (_(u'Combat: Alchemy'),_(u'Allow alchemy during combat.'),
        (u'iAllowAlchemyDuringCombat',),
        (_(u'Allow'),      1),
        (_(u'[Disallow]'), 0),
        ),
    (_(u'Combat: Max Actors'),_(u'Maximum number of actors that can actively be in combat with the player.'),
        (u'iNumberActorsInCombatPlayer',),
        (u'10',        10),
        (u'15',        15),
        (u'[20]',      20),
        (u'30',        30),
        (u'40',        40),
        (u'50',        50),
        (u'80',        80),
        (_(u'Custom'), 20),
        ),
    (_(u'Combat: Recharge Weapons'),_(u'Allow recharging weapons during combat.'),
        (u'iAllowRechargeDuringCombat',),
        (_(u'[Allow]'),  1),
        (_(u'Disallow'), 0),
        ),
    (_(u'Actor: Max Companions'),_(u'Maximum number of actors following the player.'),
        (u'iNumberActorsAllowedToFollowPlayer',),
        (u'2',         2),
        (u'4',         4),
        (u'[6]',       6),
        (u'8',         8),
        (u'10',       10),
        (_(u'Custom'), 6),
        ),
    (_(u'Crime: Alarm Distance'),
     _(u'Distance from player that NPCs (guards) will be alerted of a crime.'),
        (u'iCrimeAlarmRecDistance',),
        (u'8000',      8000),
        (u'6000',      6000),
        (u'[4000]',    4000),
        (u'3000',      3000),
        (u'2000',      2000),
        (u'1000',      1000),
        (u'500',        500),
        (_(u'Custom'), 4000),
        ),
    (_(u'Bounty: Assault'),
     _(u"Bounty for attacking a 'good' npc."),
        (u'iCrimeGoldAttack',),
        (u'[40]',      40),
        (u'100',       100),
        (u'200',       200),
        (u'300',       300),
        (u'400',       400),
        (u'500',       500),
        (u'650',       650),
        (u'800',       800),
        (_(u'Custom'), 40),
        ),
    (_(u'Crime: Prison Duration Modifier'),
     _(u'Days in prison is your bounty divided by this number.'),
        (u'iCrimeDaysInPrisonMod',),
        (u'50',         50),
        (u'60',         60),
        (u'70',         70),
        (u'80',         80),
        (u'90',         90),
        (u'[100]',     100),
        (_(u'Custom'), 100),
        ),
    (_(u'Bounty: Jailbreak'),
     _(u'Bounty for escaping from jail.'),
        (u'iCrimeGoldEscape',),
        (u'50',         50),
        (u'[100]',     100),
        (u'125',       125),
        (u'150',       150),
        (u'175',       175),
        (u'200',       200),
        (_(u'Custom'), 100),
        ),
    (_(u'Bounty: Murder'),_(u'Bounty for committing a witnessed murder.'),
        (u'iCrimeGoldMurder',),
        (u'500',       500),
        (u'750',       750),
        (u'[1000]',    1000),
        (u'1250',      1250),
        (u'1500',      1500),
        (_(u'Custom'), 1000),
        ),
    (_(u'Bounty: Pickpocketing'),
     _(u'Bounty for pickpocketing.'),
        (u'iCrimeGoldPickpocket',),
        (u'5',          5),
        (u'8',          8),
        (u'10',        10),
        (u'[25]',      25),
        (u'50',        50),
        (u'100',      100),
        (_(u'Custom'), 25),
        ),
    (_(u'Bounty: Trespassing'),_(u'Bounty for trespassing.'),
        (u'iCrimeGoldTrespass',),
        (u'1',         1),
        (u'[5]',       5),
        (u'8',         8),
        (u'10',       10),
        (u'20',       20),
        (_(u'Custom'), 5),
        ),
    (_(u'Magic: Max Resistance'),
     _(u'Maximum level of resistance a player can have to various forms of '
       u'magic and disease.'),
        (u'fPlayerMaxResistance',),
        (u'50%',       50.0),
        (u'60%',       60.0),
        (u'70%',       70.0),
        (u'80%',       80.0),
        (u'[85%]',     85.0),
        (u'90%',       90.0),
        (u'100%',     100.0),
        (_(u'Custom'), 85.0),
        ),
    (_(u'Magic: Max Summons'),
     _(u'Maximum number of creatures an actor can summon (affects both NPCs '
       u'and the player).'),
        (u'iMaxSummonedCreatures',),
        (u'[1]',       1),
        (u'3',         3),
        (u'5',         5),
        (u'8',         8),
        (u'10',       10),
        (_(u'Custom'), 1),
        ),
    (_(u'Actor: Vertical Object Detection'),
     _(u'Changes the vertical range in which NPCs detect objects. The first '
       u'value must be >= 0 and the second one must be <= 0.'),
        (u'fSandboxCylinderTop', u'fSandboxCylinderBottom',),
        (u'[x 1.0]',   150.0,     -100.0),
        (u'x 2.0',     150.0*2.0, -100.0*2.0),
        (u'x 3.0',     150.0*3.0, -100.0*3.0),
        (u'x 4.0',     150.0*4.0, -100.0*4.0),
        (u'x 5.0',     150.0*5.0, -100.0*5.0),
        (_(u'Custom'), 150.0,     -100.0),
        ),
    (_(u'Actor: Max Jump Height'),
     _(u'Increases the height to which you can jump.'),
        (u'fJumpHeightMin',),
        (u'0.5x',      38.0),
        (u'[1x]',      76.0),
        (u'2x',        152.0),
        (u'3x',        228.0),
        (u'4x',        304.0),
        (_(u'Custom'), 76.0),
        ),
    (_(u'Player: Fast Travel Time Multiplier'),
     _(u'Changes how much time passes while fast traveling. By default, it '
       u'passes ~3x slower than if you had walked the distance.'),
        (u'fFastTravelSpeedMult',),
        (_(u'[Default Speed]'), 1.0),
        (_(u'Walking Speed'),   3.5),
        (_(u'Horse Speed'),     4.0),
        (_(u'Custom'),          2.0),
        ),
    (_(u'Combat: Critical Hit Chance'),
     _(u'The chance of a strike being a critical hit.'),
        (u'fWeaponConditionCriticalChanceMult',),
        (_(u'0% (Disabled)'),     0.0),
        (u'1%',                   0.1),
        (u'5%',                   0.5),
        (u'[10%]',                0.10),
        (u'25%',                  0.25),
        (u'50%',                  0.50),
        (_(u'100% (Always)'),     1.00),
        (_(u'Custom (Max: 1.0)'), 0.10),
        ),
    (_(u'Actor: Unconsciousness Duration'),
     _(u'Time which essential NPCs stay unconscious.'),
        (u'fEssentialDeathTime',),
        (_(u'[10 Seconds]'),        10.0),
        (_(u'20 Seconds'),          20.0),
        (_(u'30 Seconds'),          30.0),
        (_(u'1 Minute'),            60.0),
        (_(u'1 1/2 Minutes'),   1.5*60.0),
        (_(u'2 Minutes'),         2*60.0),
        (_(u'3 Minutes'),         3*60.0),
        (_(u'5 Minutes'),         5*60.0),
        (_(u'Custom (in seconds)'), 10.0),
        ),
    (_(u'Compass: Recognition Distance'),
     _(u'Distance at which markers (dungeons, towns etc.) begin to show on '
       u'the compass.'),
     (u'iMapMarkerVisibleDistance',),
        (_(u'75% Shorter'),  3125),
        (_(u'50% Shorter'),  6250),
        (_(u'25% Shorter'),  9375),
        (_(u'[Default]'),    12500),
        (_(u'25% Further'),  15625),
        (_(u'50% Further'),  18750),
        (_(u'75% Further'),  21875),
        (_(u'Custom'),       12500),
        ),
    (_(u'Player: Horse Turning Speed'),
     _(u'Speed at which your horse can turn.'),
        (u'iHorseTurnDegreesPerSecond', u'iHorseTurnDegreesRampUpPerSecond',),
        (_(u'[Default]'), 45, 80),
        (u'x1.5',         68, 120),
        (u'x2',           90, 160),
        (u'x3',           135, 240),
        (_(u'Custom (Turning and ramp-up speeds)'), 45, 80),
        ),
    (_(u'Camera: PC Death Time'),
     _(u"Time after player's death before the last save is loaded."),
        (u'fPlayerDeathReloadTime',),
        (_(u'15 Seconds'),     15.0),
        (_(u'30 Seconds'),     30.0),
        (_(u'1 Minute'),       60.0),
        (_(u'5 Minute'),      300.0),
        (_(u'Unlimited'), 9999999.0),
        (_(u'Custom'),         15.0),
        ),
    (_(u'Actor: Greeting Distance'),
     _(u'Distance (in units) at which NPCs will greet the player.'),
        (u'fAIMinGreetingDistance',),
        (u'50',        50.0),
        (u'100',       100.0),
        (u'125',       125.0),
        (u'[150]',     150.0),
        (u'200',       200.0),
        (u'300',       300.0),
        (_(u'Custom'), 150.0),
        ),
    (_(u'Bounty: Horse Theft'), _(u'Bounty for horse theft.'),
        (u'iCrimeGoldStealHorse',),
        (u'10',        10),
        (u'25',        25),
        (u'50',        50),
        (u'[100]',     100),
        (u'200',       200),
        (u'250',       250),
        (u'300',       300),
        (u'450',       450),
        (_(u'Custom'), 100),
        ),
    (_(u'Player: Inventory Quantity Prompt'),
     _(u'Number of items in a stack at which point Skyrim prompts for a '
       u'quantity.'),
        (u'iInventoryAskQuantityAt',),
        (_(u'Always Prompt'), 1),
        (u'2',                2),
        (u'3',                3),
        (u'4',                4),
        (u'[5]',              5),
        (u'10',               10),
        (u'20',               20),
        (_(u'Never Prompt'),  99999),
        (_(u'Custom'),        5),
        ),
    (_(u'Player: Max Draggable Weight'),
     _(u'Maximum weight to be able move things with the drag key.'),
        (u'fMoveWeightMax',),
        (u'[115]',      115.0),
        (u'150',        150.0),
        (u'250',        250.0),
        (u'500',        500.0),
        (u'1500',      1500.0),
        (_(u'Custom'),  115.0),
        ),
    (_(u'Warning: Interior Distance to Hostiles'),
     _(u'The minimum distance hostile actors have to be to be allowed to '
       u'sleep, travel etc, when inside.'),
        (u'fHostileActorInteriorDistance',),
        (u'10',          10.0),
        (u'100',        100.0),
        (u'500',        500.0),
        (u'1000',      1000.0),
        (u'[2000]',    2000.0),
        (u'3000',      3000.0),
        (u'4000',      4000.0),
        (_(u'Custom (in units)'), 2000.0),
        ),
    (_(u'Warning: Exterior Distance to Hostiles'),
     _(u'The minimum distance hostile actors have to be to be allowed to '
       u'sleep, travel etc, when outside.'),
        (u'fHostileActorExteriorDistance',),
        (u'10',          10.0),
        (u'100',        100.0),
        (u'500',        500.0),
        (u'1000',      1000.0),
        (u'2000',      2000.0),
        (u'[3000]',    3000.0),
        (u'4000',      4000.0),
        (u'5000',      5000.0),
        (u'6000',      6000.0),
        (_(u'Custom (in units)'), 3000.0),
        ),
    (_(u'Combat: Maximum Armor Rating'),
     _(u'The Maximum amount of protection you will get from armor.'),
        (u'fMaxArmorRating',),
        (u'50',        50.0),
        (u'75',        75.0),
        (u'85',        85.0),
        (u'[90]',      90.0),
        (u'95',        95.0),
        (u'100',       100.0),
        (_(u'Custom'), 90.0),
        ),
    (_(u'Arrow: Max Arrows Attached to NPC'),
     _(u'The Maximum number of arrows that can be sticking out of an actor'),
        (u'iMaxAttachedArrows',),
        (u'[3]',       3),
        (u'10',        10.0),
        (u'30',        30.0),
        (u'50',        50.0),
        (u'100',       100.0),
        (_(u'Custom'), 3.0),
        ),
    [(_(u'Combat: AI Projectile Dodge Fix'),
      _(u'Removes the uncanny ability of NPCs to dodge projectiles being '
        u'launched at them from range.'),
        (u'fCombatDodgeChanceMax',),
        (_(u'Enabled'), 0.0),
        ),
     {u'default_enabled': True}],
    (_(u'Combat: Max Ally Hits'),
     _(u'Number of hits allowed by allies out of combat before attacking the '
       u'player.'),
        (u'iAllyHitNonCombatAllowed',),
        (u'0',         0),
        (u'[3]',       3),
        (u'5',         5),
        (u'8',         8),
        (u'10',       10),
        (u'15',       15),
        (_(u'Custom'), 3),
        ),
    (_(u'Actor: Merchant Restock Time'),
     _(u'The amount of time required for vendors to restock items and gold.'),
        (u'iDaysToRespawnVendor',),
        (_(u'Instant'),          0),
        (_(u'12 Hours'),         0.5),
        (_(u'1 Day'),            1),
        (_(u'[2 Days]'),         2),
        (_(u'4 Days'),           4),
        (_(u'1 week'),           7),
        (_(u'2 weeks'),          14),
        (_(u'1 Month'),          28),
        (_(u'Never'),            99999),
        (_(u'Custom (in days)'), 2),
        ),
    (_(u'Player: Fall Damage Threshold'),
     _(u'Changes the height at which you take fall damage.'),
        (u'fJumpFallHeightMin',),
        (u'0.5x',                 300.0),
        (_(u'[Default]'),         600.0),
        (u'2x',                   1200.0),
        (u'3x',                   1800.0),
        (u'4x',                   2400.0),
        (u'5x',                   3000.0),
        (_(u'No Fall Damage'),    99999.0),
        (_(u'Custom (in units)'), 600.0),
        ),
    (_(u'Player: Sprinting Cost'),
     _(u'Changes the stamina drain that occurs when sprinting.'),
        (u'fSprintStaminaDrainMult',),
        (_(u'None'),      0.00),
        (_(u'Halved'),    3.50),
        (_(u'[Default]'), 7.00),
        (_(u'Doubled'),   14.00),
        (_(u'Tripled'),   21.00),
        (_(u'Custom (Lower = Less Drain)'), 7.00),
        ),
    (_(u'Visuals: Masser Size'),
     _(u'Changes the size of the moon Masser (the larger one) in the night '
       u'sky.'),
        (u'iMasserSize',),
        (_(u'50% Smaller'), 45),
        (_(u'25% Smaller'), 68),
        (_(u'[Default]'),   90),
        (_(u'25% Larger'),  113),
        (_(u'50% Larger'),  135),
        (_(u'Custom'),      90),
        ),
    (_(u'Visuals: Masser Speed'),
     _(u'Changes how quickly the moon Masser (the larger one) moves in the '
       u'night sky.'),
        (u'fMasserSpeed',),
        (u'0.5x',                 0.125),
        (u'[1x]',                 0.250),
        (u'2x',                   0.500),
        (u'3x',                   0.750),
        (_(u'Custom (in units)'), 0.250),
        ),
    (_(u'Visuals: Secunda Size'),
     _(u'Changes the size of the moon Secunda (the smaller one) in the night '
       u'sky.'),
        (u'iSecundaSize',),
        (_(u'50% Smaller'), 20),
        (_(u'25% Smaller'), 30),
        (_(u'[Default]'),   40),
        (_(u'25% Larger'),  50),
        (_(u'50% Larger'),  60),
        (_(u'Custom'),      40),
        ),
    (_(u'Visuals: Secunda Speed'),
     _(u'Changes how quickly the moon Secunda (the smaller one) moves in the '
       u'night sky.'),
        (u'fSecundaSpeed',),
        (u'0.5x',                 0.15),
        (u'[1x]',                 0.3),
        (u'2x',                   0.6),
        (u'3x',                   0.9),
        (_(u'Custom (in units)'), 0.3),
        ),
    (_(u'AI: Bump Reaction Delay'),
     _(u'Changes how long it takes until NPCs (particularly followers) that '
       u'have commented on you bumping into them repeat that dialogue. '
       u'Infinite effectively disables it.'),
        (u'fBumpReactionSmallDelayTime',),
        (_(u'Infinite'), 99999.0),
        (_(u'10x Longer'),  10.0),
        (_(u'5x Longer'),    5.0),
        (_(u'[Default]'),    1.0),
        ),
    (_(u'Magic: Max Active Runes'),
     _(u'How many rune spells the player can have active simultaneously.'),
     (u'iMaxPlayerRunes',),
        (u'[1]',         1),
        (u'3',           3),
        (u'5',           5),
        (u'10',          10),
        (u'50',          50),
        (_(u'No Limit'), 99999),
        (_(u'Custom'),   1),
        ),
    (_(u'Crime: Pickpocketing Chance'),
     _(u'Improve chances of successful pickpocketing.'),
        (u'fPickPocketMinChance', u'fPickPocketMaxChance',),
        (_(u'0% to 50%'),                   0.0,  50.0),
        (_(u'0% to 75%'),                   0.0,  75.0),
        (_(u'[0% to 90%]'),                 0.0,  90.0),
        (_(u'0% to 100%'),                  0.0,  100.0),
        (_(u'25% to 100%'),                 25.0, 100.0),
        (_(u'50% to 100%'),                 50.0, 100.0),
        (_(u'Custom (Min and Max Chance)'), 0.0,  90.0),
        ),
    (_(u'Actor: Faster Shouts'),
     _(u'Decreases the time that the shout key must be held to shout multiple '
       u'words. Custom is for the first word and the rest of the shout.'),
        (u'fShoutTime1', u'fShoutTime2',),
        (_(u'4x Faster'), 0.050, 0.225),
        (_(u'2x Faster'), 0.100, 0.450),
        (_(u'[Default]'), 0.200, 0.900),
        (_(u'2x Slower'), 0.400, 1.800),
        (_(u'4x Slower'), 0.800, 3.600),
        (_(u'Custom (in milliseconds)'), 0.200, 0.900),
        ),
    (_(u'Combat: Faster Two-Handed Weapons'),
     _(u'Increases 2-hand weapon animation speed.'),
        (u'fWeaponTwoHandedAnimationSpeedMult',),
        (_(u'50% Slower'), 0.750),
        (_(u'25% Slower'), 1.125),
        (_(u'[Default]'),  1.500),
        (_(u'25% Faster'), 1.875),
        (_(u'50% Faster'), 2.250),
        (_(u'Custom'),  1.500),
        ),
    (_(u'Actor: Training Limit'),
     _(u'Maximum number of Training allowed by trainers.'),
        (u'iTrainingNumAllowedPerLevel',),
        (u'1',               1),
        (u'[5]',             5),
        (u'8',               8),
        (u'10',             10),
        (u'20',             20),
        (_(u'Unlimited'), 9999),
        (_(u'Custom'),       0),
        ),
    (_(u'Player: Underwater Breath Control'),
     _(u'How long the player can hold their breath while swimming - does not '
       u'affect Argonians.'),
        (u'fActorSwimBreathBase', u'fActorSwimBreathMult'),
        (_(u'[10 seconds]'),                 10.0, 0.30),
        (_(u'20 seconds'),                   20.0, 0.30),
        (_(u'40 seconds'),                   40.0, 0.45),
        (_(u'60 seconds'),                   60.0, 0.60),
        (_(u'Custom (Base and Multiplier)'), 10.0, 0.30)
        ),
    (_(u'Combat: Stealth Damage Bonus'),
     _(u'Increases the amount of damage you do with daggers, bows and '
       u'crossbows while sneaking.'),
        (u'fCombatSneak1HDaggerMult', u'fCombatSneakBowMult',
         u'fCombatSneakCrossbowMult'),
        (_(u'[None]'), 3.0, 2.0, 2.0),
        (u'2x',        6.0, 4.0, 4.0),
        (u'3x',        9.0, 6.0, 6.0),
        (u'4x',        12.0, 8.0, 8.0),
        (_(u'Custom (Dagger, Bow, Crossbow)'), 3.0, 2.0, 2.0),
        ),
    [(_(u'Msg: Cannot Equip Item Fix'),
      _(u"Disables the 'You cannot equip this item' message because some "
        u"Skyrim mods (e.g. Frostfall) use activatable misc objects that "
        u"require it to be disabled."),
        (u'sCantEquipGeneric',),
        (_(u'Enabled'), u''),
        ),
     {u'default_enabled': True}],
    (_(u'Msg: Auto Saving'),
     _(u'Message upon auto saving.'),
        (u'sAutoSaving',),
        (_(u'[None]'), u' '),
        (u'.',         u'.'),
        (_(u'Hmm...'), _(u'Hmm...')),
        (_(u'Custom'), _(u' ')),
        ),
    (_(u'Msg: No Fast Travel'),
     _(u'Message when attempting to fast travel when fast travel is '
       u'unavailable due to location.'),
        (u'sNoFastTravelScriptBlock',),
        (_(u'[None]'), u' '),
        (u'.',         u'.'),
        (_(u'Hmm...'), _(u'Hmm...')),
        (_(u'Custom'), _(u' ')),
        ),
    (_(u'Msg: Quick Load'),
     _(u'Message when quick loading.'),
        (u'sQuickLoading',),
        (_(u'[None]'), u' '),
        (u'.',         u'.'),
        (_(u'Hmm...'), _(u'Hmm...')),
        (_(u'Custom'), _(u' ')),
        ),
    (_(u'Msg: Quick Save'),
     _(u'Message upon quick saving.'),
        (u'sQuickSaving',),
        (_(u'[None]'), u' '),
        (u'.',         u'.'),
        (_(u'Hmm...'), _(u'Hmm...')),
        (_(u'Custom'), _(u' ')),
        ),
    (_(u'Msg: Not Enough Charge'),
     _(u'Message when enchanted item is out of charge.'),
        (u'sEnchantInsufficientCharge',),
        (_(u'[None]'), u' '),
        (u'.',         u'.'),
        (_(u'Hmm...'), _(u'Hmm...')),
        (_(u'Custom'), _(u' ')),
        ),
    (_(u'Msg: Carrying Too Much'),
     _(u'Message when you are carrying too much to run.'),
        (u'sOverEncumbered',),
        (_(u'[None]'), u' '),
        (u'.',         u'.'),
        (_(u'Hmm...'), _(u'Hmm...')),
        (_(u'Custom'), _(u' ')),
        ),
    (_(u'Cost Multiplier: Enchantment'),
     _(u'Cost factor for enchanting items.'),
        (u'fEnchantmentGoldMult',),
        (u'[10]',      10.0),
        (u'20',        20.0),
        (u'30',        30.0),
        (u'50',        50.0),
        (u'70',        70.0),
        (u'90',        90.0),
        (u'120',      120.0),
        (u'150',      150.0),
        (_(u'Custom'), 10.0),
        ),
    (_(u'Magic: Invisibility Detection Difficulty'),
     _(u'Determines how difficult it is for NPCs to see you while you are '
       u'invisible.'),
        (u'fSneakStealthBoyMult',),
        (_(u'[Impossible]'),         0.00),
        (_(u'75% Harder'),           0.25),
        (_(u'50% Harder'),           0.50),
        (_(u'25% Harder'),           0.75),
        (_(u'Nullify Invisibility'), 1.00),
        (_(u'Custom'),               0.00)
        ),
    (_(u'Bounty: Shapeshifting'),
     _(u'The bounty for transforming into a vampire lord or werewolf in front '
       u'of people.'),
        (u'iCrimeGoldWerewolf',),
        (u'500',       500),
        (u'750',       750),
        (u'[1000]',    1000),
        (u'1250',      1250),
        (u'1500',      1500),
        (_(u'Custom'), 1000),
        ),
    (_(u'Soul Trap: Lesser Soul Level'),
     _(u"The level at which NPC souls are considered 'lesser'."),
        (u'iLesserSoulActorLevel',),
        (u'[4]',       4),
        (u'16',        16),
        (u'28',        28),
        (u'38',        38),
        (_(u'Custom'), 4),
        ),
    (_(u'Soul Trap: Common Soul Level'),
     _(u"The level at which NPC souls are considered 'common'."),
        (u'iCommonSoulActorLevel',),
        (u'4',         4),
        (u'[16]',      16),
        (u'28',        28),
        (u'38',        38),
        (_(u'Custom'), 16),
        ),
    (_(u'Soul Trap: Greater Soul Level'),
     _(u"The level at which NPC souls are considered 'greater'."),
        (u'iGreaterSoulActorLevel',),
        (u'4',         4),
        (u'16',        16),
        (u'[28]',      28),
        (u'38',        38),
        (_(u'Custom'), 28),
        ),
    (_(u'Soul Trap: Grand Soul Level'),
     _(u"The level at which NPC souls are considered 'grand'."),
        (u'iGrandSoulActorLevel',),
        (u'4',         4),
        (u'16',        16),
        (u'28',        28),
        (u'[38]',      38),
        (_(u'Custom'), 38),
        ),
    (_(u'AI: Conversation Chance'),
     _(u'Chance of NPCs engaging each other in conversation.'),
        (u'fAISocialchanceForConversation',),
        (u'10%',        10.0),
        (u'[25%]',      25.0),
        (u'50%',        50.0),
        (u'100%',      100.0),
        (_(u'Custom'), 100.0),
        ),
    (_(u'AI: Conversation Chance - Interior'),
     _(u'Chance of NPCs engaging each other in conversation - in interiors.'),
        (u'fAISocialchanceForConversationInterior',),
        (u'10%',        10.0),
        (u'[25%]',      25.0),
        (u'50%',        50.0),
        (u'100%',      100.0),
        (_(u'Custom'), 100.0),
        ),
    (_(u'AI: Max Dead Actors'),
     _(u"Maximum number of dead actors allowed before they're removed."),
        (u'iRemoveExcessDeadCount', u'iRemoveExcessDeadTotalActorCount',
         u'iRemoveExcessDeadComplexTotalActorCount',
         u'iRemoveExcessDeadComplexCount', u'fRemoveExcessDeadTime',
         u'fRemoveExcessComplexDeadTime'),
        (u'[x 1]', int(15*1),   int(20*1),   int(20*1),   int(3*1),  10.0*1.0,  2.5*1.0),
        (u'x 1.5', int(15*1.5), int(20*1.5), int(20*1.5), int(3*2),  10.0*3.0,  2.5*3.0),
        (u'x 2',   int(15*2),   int(20*2),   int(20*2),   int(3*3),  10.0*5.0,  2.5*5.0),
        (u'x 2.5', int(15*2.5), int(20*2.5), int(20*2.5), int(3*4),  10.0*7.0,  2.5*7.0),
        (u'x 3',   int(15*3),   int(20*3),   int(20*3),   int(3*5),  10.0*9.0,  2.5*9.0),
        (u'x 3.5', int(15*3.5), int(20*3.5), int(20*3.5), int(3*6),  10.0*11.0, 2.5*11.0),
        (u'x 4',   int(15*4),   int(20*4),   int(20*4),   int(3*7),  10.0*13.0, 2.5*13.0),
        (_(u'Custom'), 15,          20,          20,          3,     10.0,      2.5),
        ),
    (_(u'Bounty: Theft'),
     _(u'Bounty for stealing, as fraction of item value.'),
        (u'fCrimeGoldSteal',),
        (u'1/4',      0.25),
        (u'[1/2]',     0.5),
        (u'3/4',      0.75),
        (u'1',         1.0),
        (_(u'Custom'), 0.5),
        ),
    ]

#------------------------------------------------------------------------------
# Leveled Lists
#------------------------------------------------------------------------------
listTypes = ('LVLI','LVLN','LVSP',)

#------------------------------------------------------------------------------
# Import Names
#------------------------------------------------------------------------------
# remaining to add: 'RACE',
namesTypes = {b'ACTI', b'ALCH', b'AMMO', b'APPA', b'ARMO', b'AVIF', b'BOOK',
              b'CLAS', b'CLFM', b'CONT', b'DOOR', b'ENCH', b'EXPL', b'EYES',
              b'FACT', b'FLOR', b'FURN', b'HAZD', b'HDPT', b'INGR', b'KEYM',
              b'LCTN', b'LIGH', b'MESG', b'MGEF', b'MISC', b'MSTT', b'NPC_',
              b'PERK', b'PROJ', b'SCRL', b'SHOU', b'SLGM', b'SNCT', b'SPEL',
              b'TACT', b'TREE', b'WATR', b'WEAP', b'WOOP'}

#------------------------------------------------------------------------------
# Import Prices
#------------------------------------------------------------------------------
pricesTypes = {
    'ALCH':{},'AMMO':{},'APPA':{},'ARMO':{},'BOOK':{},'INGR':{},'KEYM':{},
    'LIGH':{},'MISC':{},'SLGM':{},'WEAP':{}
    }

#------------------------------------------------------------------------------
# Import Stats
#------------------------------------------------------------------------------
statsTypes = {
        'ALCH':('eid', 'weight', 'value'),
        'AMMO':('eid', 'value', 'damage'),
        'APPA':('eid', 'weight', 'value'),
        'ARMO':('eid', 'weight', 'value', 'armorRating'),
        'BOOK':('eid', 'weight', 'value'),
        'INGR':('eid', 'weight', 'value'),
        'KEYM':('eid', 'weight', 'value'),
        'LIGH':('eid', 'weight', 'value', 'duration'),
        'MISC':('eid', 'weight', 'value'),
        'SLGM':('eid', 'weight', 'value'),
        'WEAP':('eid', 'weight', 'value', 'damage', 'speed', 'reach',
                'enchantPoints', 'stagger', 'critDamage','criticalMultiplier',
                'criticalEffect',),
    }
statsHeaders = (
    #--Alch
    (u'ALCH',
        (u'"' + u'","'.join((_(u'Type'),_(u'Mod Name'),_(u'ObjectIndex'),
        _(u'Editor Id'),_(u'Weight'),_(u'Value'))) + u'"\n')),
    #--Ammo
    (u'AMMO',
        (u'"' + u'","'.join((_(u'Type'),_(u'Mod Name'),_(u'ObjectIndex'),
        _(u'Editor Id'),_(u'Weight'),_(u'Value'))) + u'"\n')),
    #--Apparatus
    (u'APPA',
        (u'"' + u'","'.join((_(u'Type'),_(u'Mod Name'),_(u'ObjectIndex'),
        _(u'Editor Id'),_(u'Weight'),_(u'Value'))) + u'"\n')),
    #--Armo
    (u'ARMO',
        (u'"' + u'","'.join((_(u'Type'),_(u'Mod Name'),_(u'ObjectIndex'),
        _(u'Editor Id'),_(u'Weight'),_(u'Value'),_(u'armorRating'))) + u'"\n')),
    #Books
    (u'BOOK',
        (u'"' + u'","'.join((_(u'Type'),_(u'Mod Name'),_(u'ObjectIndex'),
        _(u'Editor Id'),_(u'Weight'),_(u'Value'))) + u'"\n')),
        #Ingredients
    (u'INGR',
        (u'"' + u'","'.join((_(u'Type'),_(u'Mod Name'),_(u'ObjectIndex'),
        _(u'Editor Id'),_(u'Weight'),_(u'Value'))) + u'"\n')),
    #--Keys
    (u'KEYM',
        (u'"' + u'","'.join((_(u'Type'),_(u'Mod Name'),_(u'ObjectIndex'),
        _(u'Editor Id'),_(u'Weight'),_(u'Value'))) + u'"\n')),
    #Lights
    (u'LIGH',
        (u'"' + u'","'.join((_(u'Type'),_(u'Mod Name'),_(u'ObjectIndex'),
        _(u'Editor Id'),_(u'Weight'),_(u'Value'),_(u'Duration'))) + u'"\n')),
    #--Misc
    (u'MISC',
        (u'"' + u'","'.join((_(u'Type'),_(u'Mod Name'),_(u'ObjectIndex'),
        _(u'Editor Id'),_(u'Weight'),_(u'Value'))) + u'"\n')),
    #Soulgems
    (u'SLGM',
        (u'"' + u'","'.join((_(u'Type'),_(u'Mod Name'),_(u'ObjectIndex'),
        _(u'Editor Id'),_(u'Weight'),_(u'Value'))) + u'"\n')),
    #--Weapons
    (u'WEAP',
        (u'"' + u'","'.join((_(u'Type'),_(u'Mod Name'),_(u'ObjectIndex'),
        _(u'Editor Id'),_(u'Weight'),_(u'Value'),_(u'Damage'),
        _(u'Speed'),_(u'Reach'),_(u'EPoints'))) + u'"\n')),
)

#------------------------------------------------------------------------------
# Import Sounds
#------------------------------------------------------------------------------
soundsTypes = {
    b'ACTI': (u'soundLooping', u'soundActivation'),
    "ADDN": ('ambientSound',),
    "ALCH": ('dropSound','pickupSound','soundConsume',),
    "AMMO": ('pickupSound','dropSound',),
    "APPA": ('pickupSound','dropSound',),
    "ARMA": ('footstepSound',),
    "ARMO": ('pickupSound','dropSound',),
    "ASPC": ('ambientSound','regionData','reverb',),
    "BOOK": ('pickupSound','dropSound',),
    "CONT": ('soundOpen','soundClose',),
    "DOOR": ('soundOpen','soundClose','soundLoop',),
    "EFSH": ('ambientSound',),
    "EXPL": ('sound1','sound2',),
    "FLOR": ('harvestSound',),
    "HAZD": ('sound',),
    "INGR": ('pickupSound','dropSound',),
    "IPCT": ('sound1','sound2',),
    "KEYM": ('pickupSound','dropSound',),
    "LIGH": ('sound',),
    #Needs to loop over all the sounds
    b'MGEF': (u'sounds', u'casting_sound_level'),
    # "REGN": ('entries',),
    "MISC": ('pickupSound','dropSound',),
    "MSTT": ('sound',),
    "SCRL": ('pickupSound','dropSound',),
    "SLGM": ('pickupSound','dropSound',),
    "SNCT": ('parent','staticVolumeMultiplier',),
    # Sounds does not need to loop here
    "SNDR": ('category','outputModel','sounds','looping','rumbleSendValue',
             'pctFrequencyShift','pctFrequencyVariance','priority',
             'dbVariance','staticAtten',),
    "SOPM": ('reverbSendpct','outputType','ch0_l','ch0_r','ch0_c','ch0_lFE',
             'ch0_rL','ch0_rR','ch0_bL','ch0_bR','ch1_l','ch1_r','ch1_c',
             'ch1_lFE','ch1_rL','ch1_rR','ch1_bL','ch1_bR','ch2_l','ch2_r',
             'ch2_c','ch2_lFE','ch2_rL','ch2_rR','ch2_bL','ch2_bR',
             'minDistance','maxDistance','curve1','curve2','curve3',
             'curve4','curve5',),
    "SOUN": ('soundDescriptor',),
    "TACT": ('soundLoop',),
    "TREE": ('harvestSound',),
    "WATR": ('openSound',),
    "WEAP": ('pickupSound','dropSound','attackSound','attackSound2D',
             'attackLoopSound','attackFailSound','idleSound',
             'equipSound','unequipSound','detectionSoundLevel',),
    #Needs to loop over all the sounds
    "WTHR": ('sounds',),
}

#------------------------------------------------------------------------------
# Import Cells
#------------------------------------------------------------------------------
cellRecAttrs = {
    u'C.Acoustic': (u'acousticSpace',),
    u'C.Climate': (u'climate', u'flags.showSky'),
    u'C.Encounter': (u'encounterZone',),
    u'C.ForceHideLand': (u'land_flags',),
    u'C.ImageSpace': (u'imageSpace',),
    ##: Patches unuseds?
    u'C.Light': (u'ambientRed', u'ambientGreen', u'ambientBlue', u'unused1',
                 u'directionalRed', u'directionalGreen', u'directionalBlue',
                 u'unused2', u'fogRed', u'fogGreen', u'fogBlue', u'unused3',
                 u'fogNear', u'fogFar', u'directionalXY', u'directionalZ',
                 u'directionalFade', u'fogClip', u'fogPower', u'redXplus',
                 u'greenXplus', u'blueXplus', u'unknownXplus', u'redXminus',
                 u'greenXminus', u'blueXminus', u'unknownXminus', u'redYplus',
                 u'greenYplus', u'blueYplus', u'unknownYplus', u'redYminus',
                 u'greenYminus', u'blueYminus', u'unknownYminus', u'redZplus',
                 u'greenZplus', u'blueZplus', u'unknownZplus', u'redZminus',
                 u'greenZminus', u'blueZminus', u'unknownZminus', u'redSpec',
                 u'greenSpec', u'blueSpec', u'unknownSpec', u'fresnelPower',
                 u'fogColorFarRed', u'fogColorFarGreen', u'fogColorFarBlue',
                 u'unused4', u'fogMax', u'lightFadeBegin', u'lightFadeEnd',
                 u'inherits', u'lightTemplate',),
    u'C.Location': (u'location',),
    u'C.LockList': (u'lockList',),
    u'C.MiscFlags': (u'flags.isInterior', u'flags.cantFastTravel',
                     u'flags.noLODWater', u'flags.handChanged'),
    u'C.Music': (u'music',),
    u'C.Name': (u'full',),
    u'C.Owner': (u'ownership', u'flags.publicPlace'),
    u'C.RecordFlags': (u'flags1',), # Yes seems funky but thats the way it is
    u'C.Regions': (u'regions',),
    u'C.SkyLighting': (u'skyFlags.useSkyLighting',),
    u'C.Water': (u'water', u'waterHeight', u'waterNoiseTexture',
                 u'waterEnvironmentMap', u'flags.hasWater'),
}
cell_float_attrs = {u'fogNear', u'fogFar', u'directionalFade', u'fogClip',
                    u'fogPower', u'fogMax', u'fresnelPower', u'lightFadeBegin',
                    u'lightFadeEnd', u'waterHeight'}
cell_skip_interior_attrs = {u'waterHeight'}

#------------------------------------------------------------------------------
# Import Graphics
#------------------------------------------------------------------------------
graphicsTypes = {
    b'ACTI': (u'model',),
    b'ALCH': (u'iconPath', u'model'),
    b'AMMO': (u'iconPath', u'model'),
    b'APPA': (u'iconPath', u'model'),
    b'ARMA': (u'male_model', u'female_model', u'male_model_1st',
              u'female_model_1st',),
    b'ARMO': (u'model2', u'maleIconPath', u'model4', u'femaleIconPath',
              u'addons'),
    b'BOOK': (u'iconPath', u'model'),
    b'CLAS': (u'iconPath',),
    b'CONT': (u'model',),
    b'DOOR': (u'model',),
    b'EFSH': (u'unused1', u'memSBlend', u'memBlendOp', u'memZFunc', u'fillRed',
              u'fillGreen', u'fillBlue', u'unused2', u'fillAlphaIn',
              u'fillFullAlpha', u'fillAlphaOut', u'fillAlphaRatio',
              u'fillAlphaAmp', u'fillAlphaPulse', u'fillAnimSpeedU',
              u'fillAnimSpeedV', u'edgeEffectOff', u'edgeRed', u'edgeGreen',
              u'edgeBlue', u'unused3', u'edgeAlphaIn', u'edgeFullAlpha',
              u'edgeAlphaOut', u'edgeAlphaRatio', u'edgeAlphaAmp',
              u'edgeAlphaPulse', u'fillFullAlphaRatio', u'edgeFullAlphaRatio',
              u'memDestBlend', u'partSourceBlend', u'partBlendOp',
              u'partZTestFunc', u'partDestBlend', u'partBSRampUp',
              u'partBSFull', u'partBSRampDown', u'partBSRatio',
              u'partBSPartCount', u'partBSLifetime', u'partBSLifetimeDelta',
              u'partSSpeedNorm', u'partSAccNorm', u'partSVel1', u'partSVel2',
              u'partSVel3', u'partSAccel1', u'partSAccel2', u'partSAccel3',
              u'partSKey1', u'partSKey2', u'partSKey1Time', u'partSKey2Time',
              u'key1Red', u'key1Green', u'key1Blue', u'unused4', u'key2Red',
              u'key2Green', u'key2Blue', u'unused5', u'key3Red', u'key3Green',
              u'key3Blue', u'unused6', u'colorKey1Alpha', u'colorKey2Alpha',
              u'colorKey3Alpha', u'colorKey1KeyTime', u'colorKey2KeyTime',
              u'colorKey3KeyTime', u'partSSpeedNormDelta', u'partSSpeedRotDeg',
              u'partSSpeedRotDegDelta', u'partSRotDeg', u'partSRotDegDelta',
              u'holesStart', u'holesEnd', u'holesStartVal', u'holesEndVal',
              u'edgeWidthAlphaUnit', u'edgeAlphRed', u'edgeAlphGreen',
              u'edgeAlphBlue', u'unused7', u'expWindSpeed', u'textCountU',
              u'textCountV', u'addonModelIn', u'addonModelOut',
              u'addonScaleStart', u'addonScaleEnd', u'addonScaleIn',
              u'addonScaleOut', u'ambientSound', u'key2FillRed',
              u'key2FillGreen', u'key2FillBlue', u'unused8', u'key3FillRed',
              u'key3FillGreen', u'key3FillBlue', u'unused9', u'key1ScaleFill',
              u'key2ScaleFill', u'key3ScaleFill', u'key1FillTime',
              u'key2FillTime', u'key3FillTime', u'colorScale',
              u'birthPosOffset', u'birthPosOffsetRange', u'startFrame',
              u'startFrameVariation', u'endFrame', u'loopStartFrame',
              u'loopStartVariation', u'frameCount', u'frameCountVariation',
              u'flags', u'fillTextScaleU', u'fillTextScaleV',
              u'sceneGraphDepthLimit',),
    b'FLOR': (u'model',),
    b'FURN': (u'model',),
    b'GRAS': (u'model',),
    b'INGR': (u'iconPath', u'model'),
    b'KEYM': (u'iconPath', u'model'),
    b'LIGH': (u'iconPath', u'model'),
    b'LSCR': (u'iconPath',),
    b'MGEF': (u'dual_casting_scale',),
    b'MISC': (u'iconPath', u'model'),
    b'PERK': (u'iconPath',),
    b'SLGM': (u'iconPath', u'model'),
    b'STAT': (u'model',),
    b'TREE': (u'model',),
    b'WEAP': (u'model1', u'model2', u'iconPath'),
    b'WTHR': (u'wthrAmbientColors',),
}
graphicsFidTypes = {
    b'BOOK': (u'inventoryArt',),
    b'EFSH': (u'addonModels',),
    b'MGEF': (u'menu_display_object', u'light', u'hit_shader',
              u'enchant_shader', u'projectile', u'explosion', u'casting_art',
              u'hit_effect_art', u'effect_impact_data', u'dual_casting_art',
              u'enchant_art', u'hit_visuals', u'enchant_visuals',
              u'effect_imad'),
    b'SCRL': (u'menu_display_object',),
    b'SPEL': (u'menu_display_object',),
    b'WEAP': (u'firstPersonModelObject',),
}
graphicsModelAttrs = (u'model', u'model1', u'model2', u'model4', u'male_model',
                      u'female_model', u'male_model_1st', u'female_model_1st')

#------------------------------------------------------------------------------
# Import Inventory
#------------------------------------------------------------------------------
inventoryTypes = ('NPC_','CONT',)

#------------------------------------------------------------------------------
# Import Keywords
#------------------------------------------------------------------------------
keywords_types = (b'ACTI', b'ALCH', b'AMMO', b'ARMO', b'BOOK', b'FLOR',
                  b'FURN', b'INGR', b'KEYM', b'LCTN', b'MGEF', b'MISC',
                  b'NPC_', b'RACE', b'SCRL', b'SLGM', b'SPEL', b'TACT',
                  b'WEAP',)

#------------------------------------------------------------------------------
# Import Text
#------------------------------------------------------------------------------
text_types = {
    b'ACTI': (u'activate_text_override',),
    b'ALCH': (u'description',),
    b'AMMO': (u'description',),
    b'APPA': (u'description',),
    b'ARMO': (u'description',),
    b'AVIF': (u'description',),
    b'BOOK': (u'description', u'bookText'),
    b'CLAS': (u'description',),
    #b'COLL': (u'description',), # seems fairly useless to patch this
    b'LSCR': (u'description',),
    b'MESG': (u'description',),
    b'MGEF': (u'magic_item_description',),
    b'PERK': (u'description',),
    #b'QUST': (u'description',), # no other patchers and seems unused
    # omit RACE - covered by R.Description
    b'SCRL': (u'description',),
    b'SHOU': (u'description',),
    b'SPEL': (u'description',),
    b'WEAP': (u'description',),
}

#------------------------------------------------------------------------------
# Import Object Bounds
#------------------------------------------------------------------------------
object_bounds_types = {'ACTI', 'ADDN', 'ALCH', 'AMMO', 'APPA', 'ARMO', 'ARTO',
                       'ASPC', 'BOOK', 'CONT', 'DOOR', 'DUAL', 'ENCH', 'EXPL',
                       'FLOR', 'FURN', 'GRAS', 'HAZD', 'IDLM', 'INGR', 'KEYM',
                       'LIGH', 'LVLI', 'LVLN', 'LVSP', 'MISC', 'MSTT', 'NPC_',
                       'PROJ', 'SCRL', 'SLGM', 'SOUN', 'SPEL', 'STAT', 'TACT',
                       'TREE', 'TXST', 'WEAP'}

#------------------------------------------------------------------------------
# Contents Checker
#------------------------------------------------------------------------------
# Entry types used for COBJ, CONT, LVLI and NPC_
_common_entry_types = {'ALCH', 'AMMO', 'APPA', 'ARMO', 'BOOK', 'INGR', 'KEYM',
                       'LIGH', 'LVLI', 'MISC', 'SLGM', 'SCRL', 'WEAP'}
cc_valid_types = {
    'COBJ': _common_entry_types,
    'CONT': _common_entry_types,
    'LVLN': {'LVLN', 'NPC_'},
    'LVLI': _common_entry_types,
    'LVSP': {'LVSP', 'SPEL'},
    'NPC_': _common_entry_types,
    'OTFT': {'ARMO', 'LVLI'},
}
cc_passes = (
    (('LVLN', 'LVLI', 'LVSP'), 'entries', 'listId'),
    (('COBJ', 'CONT', 'NPC_'), 'items', 'item'),
    (('OTFT',), 'items'),
)

#------------------------------------------------------------------------------
# Import Destructible
#------------------------------------------------------------------------------
destructible_types = {'ACTI', 'ALCH', 'AMMO', 'APPA', 'ARMO', 'BOOK', 'CONT',
                      'DOOR', 'FLOR', 'FURN', 'KEYM', 'LIGH', 'MISC', 'MSTT',
                      'NPC_', 'PROJ', 'SCRL', 'SLGM', 'TACT', 'WEAP'}

#------------------------------------------------------------------------------
# Import Actors
#------------------------------------------------------------------------------
actor_importer_attrs = {
    b'NPC_': {
        u'Actors.ACBS': (u'bleedoutOverride', u'calcMax', u'calcMin',
                         u'dispositionBase', u'flags.autoCalc',
                         u'flags.bleedoutOverride',
                         u'flags.doesNotAffectStealth', u'flags.doesNotBleed',
                         u'flags.essential', u'flags.female',
                         u'flags.invulnerable', u'flags.isCharGenFacePreset',
                         u'flags.isGhost', u'flags.loopedAudio',
                         u'flags.loopedScript', u'flags.oppositeGenderAnims',
                         u'flags.pcLevelMult', u'flags.protected',
                         u'flags.respawn', u'flags.simpleActor',
                         u'flags.summonable', u'flags.unique',
                         u'flags.useTemplate', u'healthOffset', u'level',
                         u'magickaOffset', u'speedMultiplier',
                         u'staminaOffset', u'templateFlags'),
        u'Actors.AIData': (u'aggression', u'aggroRadiusBehavior',
                           u'assistance', u'attack', u'confidence',
                           u'energyLevel', u'mood', u'responsibility', u'warn',
                           u'warnAttack'),
        u'Actors.CombatStyle': (u'combatStyle',),
        u'Actors.RecordFlags': (u'flags1',),
        u'Actors.Stats': (u'alchemySO', u'alchemySV', u'alterationSO',
                          u'alterationSV', u'blockSO', u'blockSV',
                          u'conjurationSO', u'conjurationSV', u'destructionSO',
                          u'destructionSV', u'enchantingSO', u'enchantingSV',
                          u'health', u'heavyArmorSO', u'heavyArmorSV',
                          u'illusionSO', u'illusionSV', u'lightArmorSO',
                          u'lightArmorSV', u'lockpickingSO', u'lockpickingSV',
                          u'magicka', u'marksmanSO', u'marksmanSV',
                          u'oneHandedSO', u'oneHandedSV', u'pickpocketSO',
                          u'pickpocketSV', u'restorationSO', u'restorationSV',
                          u'smithingSO', u'smithingSV', u'sneakSO', u'sneakSV',
                          u'speechcraftSO', u'speechcraftSV', u'stamina',
                          u'twoHandedSO', u'twoHandedSV'),
        u'NPC.AIPackageOverrides': (u'spectator', u'observe', u'guardWarn',
                                    u'combat'),
        u'NPC.Class': (u'iclass',),
        u'NPC.Race': (u'race',),
    },
}
actor_types = ('NPC_',)

#------------------------------------------------------------------------------
# Import Spell Stats
#------------------------------------------------------------------------------
spell_stats_attrs = (u'eid', u'cost', u'spellType', u'chargeTime', u'castType',
                     u'targetType', u'castDuration', u'range', u'halfCostPerk',
                     u'dataFlags')
spell_stats_types = {b'SCRL', b'SPEL'}

#------------------------------------------------------------------------------
# Tweak Actors
#------------------------------------------------------------------------------
actor_tweaks = {
    u'OppositeGenderAnimsPatcher_Female',
    u'OppositeGenderAnimsPatcher_Male',
}

#------------------------------------------------------------------------------
# Tweak Assorted
#------------------------------------------------------------------------------
assorted_tweaks = {
    u'AssortedTweak_ArmorPlayable',
    u'AssortedTweak_NoLightFlicker',
    u'AssortedTweak_PotionWeight',
    u'AssortedTweak_IngredientWeight',
    u'AssortedTweak_PotionWeightMinimum',
    u'AssortedTweak_StaffWeight',
    u'AssortedTweak_ArrowWeight',
    u'AssortedTweak_HarvestChance',
    u'AssortedTweak_WindSpeed',
    u'AssortedTweak_UniformGroundcover',
    u'AssortedTweak_SetSoundAttenuationLevels',
    u'AssortedTweak_SetSoundAttenuationLevels_NirnrootOnly',
    u'AssortedTweak_LightFadeValueFix',
    u'AssortedTweak_TextlessLSCRs',
}
staff_condition = (u'animationType', 8)

#------------------------------------------------------------------------------
# Import Relations
#------------------------------------------------------------------------------
relations_attrs = (u'faction', u'mod', u'group_combat_reaction')
relations_csv_header = u'"%s","%s","%s","%s","%s","%s","%s","%s"\n' % (
    _(u'Main Eid'), _(u'Main Mod'), _(u'Main Object'), _(u'Other Eid'),
    _(u'Other Mod'), _(u'Other Object'), _(u'Modifier'),
    _(u'Group Combat Reaction'))
relations_csv_row_format = u'"%s","%s","0x%06X","%s","%s","0x%06X","%s","%s"\n'

#------------------------------------------------------------------------------
# Import Enchantment Stats
#------------------------------------------------------------------------------
ench_stats_attrs = (u'enchantmentCost', u'generalFlags', u'castType',
                    u'enchantmentAmount', u'targetType', u'enchantType',
                    u'chargeTime', u'baseEnchantment', u'wornRestrictions')

#--------------------------------------------------------------------------
# Import Effect Stats
#--------------------------------------------------------------------------
mgef_stats_attrs = (u'flags', u'base_cost', u'associated_item', u'magic_skill',
                    u'resist_value', u'taper_weight', u'minimum_skill_level',
                    u'spellmaking_area', u'spellmaking_casting_time',
                    u'taper_curve', u'taper_duration', u'second_av_weight',
                    u'effect_archetype', u'actorValue', u'casting_type',
                    u'delivery', u'second_av', u'skill_usage_multiplier',
                    u'equip_ability', u'perk_to_apply',
                    u'script_effect_ai_score', u'script_effect_ai_delay_time')

# Record type to name dictionary
record_type_name = {
    b'ALCH': _(u'Ingestibles'),
    b'AMMO': _(u'Ammo'),
    b'APPA': _(u'Apparatuses'),
    b'ARMO': _(u'Armors'),
    b'BOOK': _(u'Books'),
    b'INGR': _(u'Ingredients'),
    b'KEYM': _(u'Keys'),
    b'LIGH': _(u'Lights'),
    b'MISC': _(u'Misc'),
    b'SLGM': _(u'Soulgems'),
    b'SPEL': _(u'Spells'),
    b'WEAP': _(u'Weapons'),
}
