# -*- coding: utf-8 -*-
#
# GPL License and Copyright Notice ============================================
#  This file is part of Wrye Bash.
#
#  Wrye Bash is free software: you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation, either version 3
#  of the License, or (at your option) any later version.
#
#  Wrye Bash is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Wrye Bash.  If not, see <https://www.gnu.org/licenses/>.
#
#  Wrye Bash copyright (C) 2005-2009 Wrye, 2010-2024 Wrye Bash Team
#  https://github.com/wrye-bash
#
# =============================================================================
"""This module lists the files installed in the Data folder in a completely
vanilla Starfield setup."""
import os

vanilla_files = {f.replace('\\', os.sep) for f in {
    'BlueprintShips-Starfield - Localization.ba2',
    'BlueprintShips-Starfield.esm',
    'Constellation - Localization.ba2',
    'Constellation - Textures.ba2',
    'Constellation.esm',
    'CreationKit - Shaders.ba2',
    'data.bin',
    'OldMars - Localization.ba2',
    'OldMars - Textures.ba2',
    'OldMars.esm',
    'SFBGS003 - Main.ba2',
    'SFBGS003 - Textures.ba2',
    'SFBGS003 - Voices_de.ba2',
    'SFBGS003 - Voices_en.ba2',
    'SFBGS003 - Voices_es.ba2',
    'SFBGS003 - Voices_fr.ba2',
    'SFBGS003 - Voices_ja.ba2',
    'SFBGS003.esm',
    'SFBGS006 - Main.ba2',
    'SFBGS006 - Textures.ba2',
    'SFBGS006.esm',
    'SFBGS007 - Main.ba2',
    'SFBGS007.esm',
    'SFBGS008 - Main.ba2',
    'SFBGS008.esm',
    'Starfield - Animations.ba2',
    'Starfield - DensityMaps.ba2',
    'Starfield - FaceAnimation01.ba2',
    'Starfield - FaceAnimation02.ba2',
    'Starfield - FaceAnimation03.ba2',
    'Starfield - FaceAnimation04.ba2',
    'Starfield - FaceAnimationPatch.ba2',
    'Starfield - FaceMeshes.ba2',
    'Starfield - GeneratedTextures.ba2',
    'Starfield - Interface.ba2',
    'Starfield - Localization.ba2',
    'Starfield - LODMeshes.ba2',
    'Starfield - LODMeshesPatch.ba2',
    'Starfield - LODTextures.ba2',
    'Starfield - LODTextures01.ba2',
    'Starfield - LODTextures02.ba2',
    'Starfield - Materials.ba2',
    'Starfield - Meshes01.ba2',
    'Starfield - Meshes02.ba2',
    'Starfield - MeshesPatch.ba2',
    'Starfield - Misc.ba2',
    'Starfield - Particles.ba2',
    'Starfield - ParticlesTestData.ba2',
    'Starfield - PlanetData.ba2',
    'Starfield - Shaders.ba2',
    'Starfield - ShadersBeta.ba2',
    'Starfield - Terrain01.ba2',
    'Starfield - Terrain02.ba2',
    'Starfield - Terrain03.ba2',
    'Starfield - Terrain04.ba2',
    'Starfield - TerrainPatch.ba2',
    'Starfield - Textures01.ba2',
    'Starfield - Textures02.ba2',
    'Starfield - Textures03.ba2',
    'Starfield - Textures04.ba2',
    'Starfield - Textures05.ba2',
    'Starfield - Textures06.ba2',
    'Starfield - Textures07.ba2',
    'Starfield - Textures08.ba2',
    'Starfield - Textures09.ba2',
    'Starfield - Textures10.ba2',
    'Starfield - Textures11.ba2',
    'Starfield - TexturesPatch.ba2',
    'Starfield - Voices01.ba2',
    'Starfield - Voices02.ba2',
    'Starfield - VoicesPatch.ba2',
    'Starfield - WwiseSounds01.ba2',
    'Starfield - WwiseSounds02.ba2',
    'Starfield - WwiseSounds03.ba2',
    'Starfield - WwiseSounds04.ba2',
    'Starfield - WwiseSounds05.ba2',
    'Starfield - WwiseSoundsPatch.ba2',
    'Starfield.esm',
    'DataViews\\ObjectWindow\\_common\\Loc-Dungeons.filter',
    'DataViews\\ObjectWindow\\_common\\Loc-OEWorlds.filter',
    'DataViews\\ObjectWindow\\_common\\Planets-Life.filter',
    'EditorFiles\\Bundles\\Age & Lifetime.pofx',
    'EditorFiles\\Bundles\\Alpha Curve with EmitterCycle.pofx',
    'EditorFiles\\Bundles\\AlphaByCurve.pofx',
    'EditorFiles\\Bundles\\Basic Init.pofx',
    'EditorFiles\\Bundles\\BiDirectionalRotation.pofx',
    'EditorFiles\\Bundles\\Cylinder.pofx',
    'EditorFiles\\Bundles\\Drag.pofx',
    'EditorFiles\\Bundles\\Flipbook Settings with Curve.pofx',
    'EditorFiles\\Bundles\\Flipbook Settings.pofx',
    'EditorFiles\\Bundles\\FlipBook.pofx',
    'EditorFiles\\Bundles\\Flipbook_TimeBased_OverAge.pofx',
    'EditorFiles\\Bundles\\GAME_Wind_AsForce.pofx',
    'EditorFiles\\Bundles\\GAME_Wind_AsVelocity.pofx',
    'EditorFiles\\Bundles\\Gravity.pofx',
    'EditorFiles\\Bundles\\Line Attractor.pofx',
    'EditorFiles\\Bundles\\Point Attractor.pofx',
    'EditorFiles\\Bundles\\Ribbon.pofx',
    'EditorFiles\\Bundles\\Rotation.pofx',
    'EditorFiles\\Bundles\\Scale Parameters.pofx',
    'EditorFiles\\Bundles\\ScaleBySpawnShape.pofx',
    'EditorFiles\\Bundles\\StretchByVelocity.pofx',
    'EditorFiles\\Bundles\\Turbulence_SineBased.pofx',
    'EditorFiles\\Bundles\\UVScroll.pofx',
    'EditorFiles\\Bundles\\Velocity.pofx',
    'EditorFiles\\Bundles\\Variables\\BeamProjectileVars.pofx',
    'EditorFiles\\Bundles\\Variables\\EmitterProjectileVars.pofx',
    'EditorFiles\\Particles\\ParticlesLODCurves.json',
    'EditorFiles\\Particles\\ParticlesLODPresets.json',
    'EditorFiles\\Primitives\\VCPreviewCube01.nif',
    'EditorFiles\\Primitives\\VCPreviewCylinder01.nif',
    'EditorFiles\\Primitives\\VCPreviewPlane01.nif',
    'EditorFiles\\Primitives\\VCPreviewSphere01.nif',
    'EditorFiles\\RuleTemplates\\Bundles\\Age & Lifetime.json',
    'EditorFiles\\RuleTemplates\\Bundles\\Basic Init.json',
    'EditorFiles\\RuleTemplates\\Bundles\\BiDirectionalRotation.json',
    'EditorFiles\\RuleTemplates\\Bundles\\Drag.json',
    'EditorFiles\\RuleTemplates\\Bundles\\Gravity.json',
    'EditorFiles\\RuleTemplates\\Bundles\\Line Attractor.json',
    'EditorFiles\\RuleTemplates\\Bundles\\Point Attractor.json',
    'EditorFiles\\RuleTemplates\\Bundles\\Ribbon.json',
    'EditorFiles\\RuleTemplates\\Bundles\\Rotation.json',
    'EditorFiles\\RuleTemplates\\Bundles\\UVScroll.json',
    'EditorFiles\\RuleTemplates\\Bundles\\Velocity.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerEffect.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerEffectEmissive.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerEffectEmissiveOnly.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerEffectEmissiveOnlyRemap.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerEffectEmissiveRemap.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerEffectGlass.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerEffectGlassNoFrost.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerEffectRemap.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerEyebrow.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerMouth.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerPlanetDecal.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerStandard.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerStandardDecal.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\1LayerStandardDecalEmissive.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\2LayerEffect.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\2LayerEffectEmissive.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\2LayerEffectEmissiveOnly.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\2LayerEffectEmissiveOnlyRemap.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\2LayerEffectEmissiveRemap.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\2LayerEffectRemap.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\2LayerPlanetDecal.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\2LayerStandard.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\2LayerStandardEmissive.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\3LayerEffect.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\3LayerEffectEmissive.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\3LayerEffectEmissiveOnly.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\3LayerPlanetDecal.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\3LayerStandard.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\3LayerStandardEmissive.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\4LayerPlanetDecal.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\4LayerStandard.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\BaseMaterial.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\BodySkin1Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Character2Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Character3Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Character4Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\CloudCard.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\ColorEmissive.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Debug.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Experimental.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Eye1Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\EyeWetness1Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\GlobalLayer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Hair1Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Invisible.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Occlusion.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\PlanetaryRing.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Skin5Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\StarmapBodyEffect.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Terrain1Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\TerrainEmissive1Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\TranslucentThin1Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\TranslucentTwoSided1Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\TwoSided1Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\VegetationEmissive1Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\VegetationEmissive2Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\VegetationStandard1Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\VegetationStandard2Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\VegetationTranslucent1Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\VegetationTranslucent2Layer.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Water.json',
    'EditorFiles\\RuleTemplates\\ShaderModels\\Water1Layer.json',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\AkilaCity.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\CydoniaCity.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DefaultSpaceshipLandingOverlay.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR001World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR002World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR003CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR003CaveWorldC.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR003CaveWorldD.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR006World03.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR007World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR008World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR009World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR010World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR011World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR012World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR014GarageWorldB.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR015World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR016World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR017World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR018World01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR020WorldNew.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR021World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR022World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR023World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR024BountyHunters.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR024World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR025World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR026World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR027World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR029World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR034World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\DR035World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LandingOverlay01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LandingOverlay02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LandingOverlay03.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LandingOverlay04.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LandingOverlay05.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC001World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC003KreetBase.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC006World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC017World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC024World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC028AbandonedMines.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC028DrillExit.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC028FreightElevatorExit.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC030World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC032LondinionBWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC042BattleofNiira.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC062TauGourmetWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC070World01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC071World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC074World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC092World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC093KazaalSulfurMineWorldB.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC116World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC119TheMantisLairWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC123World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC124World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC125World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC126World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC127World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC131World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC132World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC133World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC134World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC135World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC136World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC139World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC142World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC143World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC144World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC146World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC148World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC151World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC152World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC153World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC154World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC155World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC159World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC160World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC161World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC164World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC165World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC166World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC167World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC171World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC172World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC173World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC174World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC176World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC178World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC179World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\LC180World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\NeonCity.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\NewAtlantis.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF001CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF002CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF003CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF004CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF005CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF006CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF007CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF008CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF009CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF010CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF011CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF014CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF015World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF016World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF017World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF018World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF019World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF020World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF021World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF022World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF023World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF024World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF025World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAF026World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAH001World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEAH002World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB001World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB002World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB003World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB004World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB005World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB007World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB008World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB009World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB010World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB011World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB012World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB013World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB014World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB015World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB016World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB017World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB018World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB019World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB020World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB021World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB022World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB023World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB024World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB026World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB027World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB028World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB029World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB030World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB031World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB032World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEBB034World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDB001World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDB002World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDB502World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDB503World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDB505World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDB506World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDB507World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDB508World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDB509World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDB510World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDB511World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDebugNaturalOverlay.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDebugOverlay.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEDebugShipwreckOverlay.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM001World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM002World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM003World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM004World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM005World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM006World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM007World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM008World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM009World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM010World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM011World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM012World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM013World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM014World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJM015World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP001CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP002World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP004CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP005CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP006CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP008CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP017World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP018World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP019World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP020World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP021World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP022World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP023World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP024World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP025World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP026World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP027World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP029World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP030World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP031World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP032World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEJP033World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEKMK002SupplyMissionWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEOB001World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEOB002CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEOB003CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEOB004CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEOB005CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEOB006World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEOB007World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEOB008World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESC001World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESC002World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESC003World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD001CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD003CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD007CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD008World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD009World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD010World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD011World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD012World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD013World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD014World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD015World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD016World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD017World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESD018World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESF001World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESF002World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESF003World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESF004World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESF005World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESF006World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESF007World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESF008World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESF009World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OESF010World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEZW001CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEZW002CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEZW003CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEZW004CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEZW006CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEZW007CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEZW008CaveWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OEZW009World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayBlockOverlayPOIBiomeDenRough03.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayBlockPOIBiomeOasis01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayCraterCaveEntrance01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayCratersSharpCaveEntrance01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayFieldsFractureCaveEntrance01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayFieldsHillsCaveEntrance01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayFieldsHillsCaveEntrance03.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayHillsRockyCaveEntrance01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayHillsRoundedCaveEntrance01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayHillsRoundedCaveEntrance02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayHillsSharpCaveEntrance01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeArch01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeCraterGrove01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeCrystalCave1.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeCrystalTrees01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenLayered01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenLayered02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenPocked01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenPocked02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenRough01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenRough02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenSharp01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenSharp02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenSharp03.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenVeiny01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenVeiny02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenVolcanicRough01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenVolcanicRough02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenVolcanicWorn01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeDenVolcanicWorn02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeFairyRing01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeFloraGrove01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisLayered01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisLayered02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisPocked01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisPocked02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisRough01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisRough02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisSharp01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisSharp02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisVeiny01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisVeiny02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisVolcanicRough01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisVolcanicRough02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisVolcanicWorn01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeOasisVolcanicWorn02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeStrangeValley01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayPOIBiomeValleyofTrees01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitAeriformLifeMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitAeriformLifeSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitAeriformLifeSm02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitAmphibiousFootholdMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitAmphibiousFootholdMed02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitAmphibiousFootholdSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitBoiledSeasMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitBoiledSeasMed02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitBoiledSeasSm01new.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitBolideBombardmentMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitBolideBombardmentMed01Life.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitBolideBombardmentMed02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitBolideBombardmentMed02Life.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitBolideBombardmentMed03.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitBolideBombardmentMed03Life.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitCharredEcosystemMd01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitCharredEcosystemMd01Water.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitCharredEcosystemMd02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitCharredEcosystemMd02Water.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitCharredEcosystemSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitCharredEcosystemSm01Water.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitContinualConducterMd01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitContinualConductorSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitContinualConductorSm02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitContualConductorSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitCorallineLandmassMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitCorallineLandmassMed02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitCorallineLandmassMed03.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitCrystallineCrustLg01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitCrystallineCrustLg02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitCrystallineCrustSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitDiseasedBiosphereMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitDiseasedBiosphereMed02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitDiseasedBiosphereSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitEcologicalConsortiumMd01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitEcologicalConsortiumSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitEcologicalConsortiumSm02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitEmergingTectonicsMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitEmergingTectonicsMed02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitEmergingTectonicsSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitEnergeticRiftingMd01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitEnergeticRiftingMd02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitEnergeticRiftingMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitEnergeticRiftingSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitEnergeticRiftingSm02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitExtinctionEventMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitExtinctionEventMed02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitExtinctionEventSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitFrozenEcosystemMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitFrozenEcosystemSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitFrozenEcosystemSm02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitGaseousFontMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitGaseousFontMed02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitGaseousFontMed03new.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitGlobalGlacialRecessionMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitGlobalGlacialRecessionSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitGlobalGlacialRecessionSm02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitGravitationalAnomalySm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitGravitationalAnomalySm02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitGravitationalAnomalySm03.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPeltedFieldMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPeltedFieldMed01Water.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPeltedFieldSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPeltedFieldSm01Water.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPeltedFieldSm02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPeltedFieldSm02Water.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPrimedforLifeMd01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPrimedLifeMd01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPrimedLifeMd02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPrimedLifeSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPrimordialNetworkMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPrimordialNetworkMed02new.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPrimordialNetworkSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPrismaticPlumesMd01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPrismaticPlumesSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPrismaticPlumesSm02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPsychotropicBiotaMed01new.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPsychotropicBiotaSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitPsychotropicBiotaSm02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSentientMicrobialColoniesLg01new.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSentientMicrobialColoniesMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSentientMicrobialColoniesMed02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSlushySubsurfaceSeasMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSlushySubsurfaceSeasSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSlushySubsurfaceSeasSm02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSolarStormsSeasonsLg01Life.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSolarStormsSeasonsLg01new.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSolarStormsSeasonsMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSolarStormsSeasonsMed01Life.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSolarStormsSeasonsMed02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSolarStormsSeasonsMed02Life.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSonorousLilthosphereMed02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSonorousLithosphereMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitSonorousLithosphereSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitTurbulentLithosphereMed01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitTurbulentLithosphereSm01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\OverlayTraitTurbulentLithosphereSm02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\PCMGenericLandingOverlay.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\PCMGenericLandingUndiscoveredOverlay.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\PCMHazardTestOverlay.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\PCMShipLanding01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\PCMShipLanding02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\PCMShipLanding03.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\PCMShipLanding04.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\POI001World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\POIJP003World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\POIJP007World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\POIJP009World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\POIJP010World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\POIJP011World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\POIJP012World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\POIJP013World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\POIJP014World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\POIJP015World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\POIJP016World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL003World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL005MuybridgeWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL010World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL012World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL018Worlda.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL032World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL036World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL037World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL039World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL040World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL064World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL067World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL089WorldNEW.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\RL090World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB001TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB002TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB003TempleWorld02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB004TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB005TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB006TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB007TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB008TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB009TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB010TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB011TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB012TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB013TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB014TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB015TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SB016TempleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SettleCrucibleWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SettleGagarinWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\settlehopetownworld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SettleNewHomesteadWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SettleParadisoWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SettleRedMile.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SettleTheEleosRetreatWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\SettleWaggonerFarm.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestAirlockAIPathing.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestJustin3x3World.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestJustinWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestLandscape.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestLandscapeDUPE.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestLightingGIWorld02.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestMikeLandingOverlay.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestMikeLandingOverlayDUPE.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestMikeOverlayRenamed.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestOverlaySmallCave.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestRocksRoughWorld01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestSalvatore.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestStarshipLandedWorld.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestVecteraVista01.tif',
    'Source\\TGATextures\\Terrain\\OverlayMasks\\TestWaterWorld.tif',
    'Textures\\BrushAlphas\\BillowyNoise.dds',
    'Textures\\BrushAlphas\\Circle.dds',
    'Textures\\BrushAlphas\\Circle02.DDS',
    'Textures\\BrushAlphas\\CircleHard.dds',
    'Textures\\BrushAlphas\\CircleHemisphere.dds',
    'Textures\\BrushAlphas\\CloudSpray.dds',
    'Textures\\BrushAlphas\\Clumpiness.dds',
    'Textures\\BrushAlphas\\CropRow01.dds',
    'Textures\\BrushAlphas\\GrassyMound.dds',
    'Textures\\BrushAlphas\\MeadowNoise.dds',
    'Textures\\BrushAlphas\\Oval01_d.dds',
    'Textures\\BrushAlphas\\Pyramid.dds',
    'Textures\\BrushAlphas\\Road.dds',
    'Textures\\BrushAlphas\\RoadDirt.dds',
    'Textures\\BrushAlphas\\RoadTireTracks02.dds',
    'Textures\\BrushAlphas\\Splatter.dds',
    'Textures\\BrushAlphas\\Splatter2.dds',
    'Textures\\BrushAlphas\\Square.dds',
    'Textures\\BrushAlphas\\SquareHard.dds',
    'Textures\\Motd_Media\\MOTDImage.png',
    'video\\ArtifactVision01.bk2',
    'video\\ArtifactVision02.bk2',
    'video\\ArtifactVision03.bk2',
    'video\\ArtifactVision04.bk2',
    'video\\ArtifactVision05.bk2',
    'video\\ArtifactVision06.bk2',
    'video\\ArtifactVision07.bk2',
    'video\\ArtifactVision08.bk2',
    'video\\ArtifactVision09.bk2',
    'video\\BGS_LOGO_1080p_BinkVersion.bk2',
    'video\\EndingVision.bk2',
    'video\\MainMenuLoop.bk2',
    'video\\PowerVision_Alien.bk2',
    'video\\PowerVision_AntiGravField.bk2',
    'video\\PowerVision_CreateVac.bk2',
    'video\\PowerVision_CreatorsPeace.bk2',
    'video\\PowerVision_Earthbound.bk2',
    'video\\PowerVision_Elemental.bk2',
    'video\\PowerVision_Eternal.bk2',
    'video\\PowerVision_GravDash.bk2',
    'video\\PowerVision_GravityWave.bk2',
    'video\\PowerVision_GravityWell.bk2',
    'video\\PowerVision_InnerDemon.bk2',
    'video\\PowerVision_LifeForced.bk2',
    'video\\PowerVision_MoonForm.bk2',
    'video\\PowerVision_ParallelSelf.bk2',
    'video\\PowerVision_ParticleBeam.bk2',
    'video\\PowerVision_PersonalAtmosphere.bk2',
    'video\\PowerVision_PhasedTime.bk2',
    'video\\PowerVision_Precognition.bk2',
    'video\\PowerVision_ReactiveShield.bk2',
    'video\\PowerVision_SenseStar.bk2',
    'video\\PowerVision_SolarFlare.bk2',
    'video\\PowerVision_SunlessSpace.bk2',
    'video\\PowerVision_Supernova.bk2',
    'video\\PowerVision_VoidForm.bk2',
}}
