# -*- coding: utf-8 -*-
#
# GPL License and Copyright Notice ============================================
#  This file is part of Wrye Bash.
#
#  Wrye Bash is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 2
#  of the License, or (at your option) any later version.
#
#  Wrye Bash is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Wrye Bash; if not, write to the Free Software Foundation,
#  Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#  Wrye Bash copyright (C) 2005-2009 Wrye, 2010-2019 Wrye Bash Team
#  https://github.com/wrye-bash
#
# =============================================================================
"""This module lists the files installed in the Data folder in a completely
vanilla Fallout NV setup."""

#--Every file in the Data directory from Bethsoft
vanilla_files = {
    # Section 1: Vanilla files
    u'Credits.txt',
    u'CreditsWacky.txt',
    u'Fallout - Invalidation.bsa',
    u'Fallout - Meshes.bsa',
    u'Fallout - Meshes2.bsa',
    u'Fallout - Misc.bsa',
    u'Fallout - Sounds.bsa',
    u'Fallout - Textures.bsa',
    u'Fallout - Textures2.bsa',
    u'Fallout - Voices1.bsa',
    u'FalloutNV.esm',
    u'Update.bsa',
    u'Music\\BTTL\\Evil1\\mus_BTTL_Lp_Evil1_City_Full.mp3',
    u'Music\\BTTL\\Evil1\\mus_BTTL_Lp_Evil1_City_Perc.mp3',
    u'Music\\BTTL\\Evil1\\mus_BTTL_Lp_Evil1_Rural_Full(alt1).mp3',
    u'Music\\BTTL\\Evil1\\mus_BTTL_Lp_Evil1_Rural_Full.mp3',
    u'Music\\BTTL\\Evil1\\mus_BTTL_Lp_Evil1_Rural_Perc(alt1).mp3',
    u'Music\\BTTL\\Evil1\\mus_BTTL_Lp_Evil1_Rural_Perc(alt2).mp3',
    u'Music\\BTTL\\Evil1\\mus_BTTL_Lp_Evil1_Rural_Perc.mp3',
    u'Music\\BTTL\\Evil2\\mus_BTTL_Lp_Evil2_City_Full.mp3',
    u'Music\\BTTL\\Evil2\\mus_BTTL_Lp_Evil2_City_Perc.mp3',
    u'Music\\BTTL\\Evil2\\mus_BTTL_Lp_Evil2_Rural_Full(alt1).mp3',
    u'Music\\BTTL\\Evil2\\mus_BTTL_Lp_Evil2_Rural_Full.mp3',
    u'Music\\BTTL\\Evil2\\mus_BTTL_Lp_Evil2_Rural_Perc(alt1).mp3',
    u'Music\\BTTL\\Evil2\\mus_BTTL_Lp_Evil2_Rural_Perc.mp3',
    u'Music\\BTTL\\Evil3\\mus_BTTL_Lp_Evil3_City_Full.mp3',
    u'Music\\BTTL\\Evil3\\mus_BTTL_Lp_Evil3_City_Perc.mp3',
    u'Music\\BTTL\\Evil3\\mus_BTTL_Lp_Evil3_Rural_Full.mp3',
    u'Music\\BTTL\\Evil3\\mus_BTTL_Lp_Evil3_Rural_Perc.mp3',
    u'Music\\BTTL\\Evil4\\mus_BTTL_Lp_Evil4_City_Full.mp3',
    u'Music\\BTTL\\Evil4\\mus_BTTL_Lp_Evil4_City_Perc.mp3',
    u'Music\\BTTL\\Evil4\\mus_BTTL_Lp_Evil4_Rural_Full.mp3',
    u'Music\\BTTL\\Evil4\\mus_BTTL_Lp_Evil4_Rural_Perc.mp3',
    u'Music\\BTTL\\Good1\\mus_BTTL_Lp_Good1_City_Full.mp3',
    u'Music\\BTTL\\Good1\\mus_BTTL_Lp_Good1_City_Perc.mp3',
    u'Music\\BTTL\\Good1\\mus_BTTL_Lp_Good1_Rural_Full.mp3',
    u'Music\\BTTL\\Good1\\mus_BTTL_Lp_Good1_Rural_Perc.mp3',
    u'Music\\BTTL\\Good2\\mus_BTTL_Lp_Good2_City_Full.mp3',
    u'Music\\BTTL\\Good2\\mus_BTTL_Lp_Good2_City_Perc.mp3',
    u'Music\\BTTL\\Good2\\mus_BTTL_Lp_Good2_Rural_Full(alt1).mp3',
    u'Music\\BTTL\\Good2\\mus_BTTL_Lp_Good2_Rural_Full.mp3',
    u'Music\\BTTL\\Good2\\mus_BTTL_Lp_Good2_Rural_Perc(alt1).mp3',
    u'Music\\BTTL\\Good2\\mus_BTTL_Lp_Good2_Rural_Perc.mp3',
    u'Music\\BTTL\\Good3\\mus_BTTL_Lp_Good3_City_Full.mp3',
    u'Music\\BTTL\\Good3\\mus_BTTL_Lp_Good3_City_Perc.mp3',
    u'Music\\BTTL\\Good3\\mus_BTTL_Lp_Good3_Rural_Full.mp3',
    u'Music\\BTTL\\Good3\\mus_BTTL_Lp_Good3_Rural_Perc.mp3',
    u'Music\\BTTL\\Good4\\mus_BTTL_Lp_Good4_City_Full.mp3',
    u'Music\\BTTL\\Good4\\mus_BTTL_Lp_Good4_City_Perc.mp3',
    u'Music\\BTTL\\Good4\\mus_BTTL_Lp_Good4_Rural_Full.mp3',
    u'Music\\BTTL\\Good4\\mus_BTTL_Lp_Good4_Rural_Perc.mp3',
    u'Music\\DNGN\\Dungeon1\\mus_DNGN_One_1Low(alt).mp3',
    u'Music\\DNGN\\Dungeon1\\mus_DNGN_One_1Low.mp3',
    u'Music\\DNGN\\Dungeon1\\mus_DNGN_One_2Mid.mp3',
    u'Music\\DNGN\\Dungeon1\\mus_DNGN_One_3High.mp3',
    u'Music\\DNGN\\Dungeon2\\mus_DNGN_Two_1Low(alt1).mp3',
    u'Music\\DNGN\\Dungeon2\\mus_DNGN_Two_1Low.mp3',
    u'Music\\DNGN\\Dungeon2\\mus_DNGN_Two_2Mid.mp3',
    u'Music\\DNGN\\Dungeon2\\mus_DNGN_Two_3High.mp3',
    u'Music\\DNGN\\Dungeon3\\mus_DNGN_Three_1Low.mp3',
    u'Music\\DNGN\\Dungeon3\\mus_DNGN_Three_2Mid(alt1).mp3',
    u'Music\\DNGN\\Dungeon3\\mus_DNGN_Three_2Mid.mp3',
    u'Music\\DNGN\\Dungeon3\\mus_DNGN_Three_3High.mp3',
    u'Music\\DNGN\\Dungeon4\\mus_DNGN_Four_1Low.mp3',
    u'Music\\DNGN\\Dungeon4\\mus_DNGN_Four_2Mid.mp3',
    u'Music\\DNGN\\Dungeon4\\mus_DNGN_Four_3High.mp3',
    u'Music\\DNGN\\Dungeon5\\mus_DNGN_Five_1Low.mp3',
    u'Music\\DNGN\\Dungeon5\\mus_DNGN_Five_2Mid(alt1).mp3',
    u'Music\\DNGN\\Dungeon5\\mus_DNGN_Five_2Mid.mp3',
    u'Music\\DNGN\\Dungeon5\\mus_DNGN_Five_3High.mp3',
    u'Music\\DNGN\\Dungeon6\\mus_DNGN_Six_1Low.mp3',
    u'Music\\DNGN\\Dungeon6\\mus_DNGN_Six_2Mid.mp3',
    u'Music\\DNGN\\Dungeon6\\mus_DNGN_Six_3High.mp3',
    u'Music\\DNGN\\Dungeon7\\mus_DNGN_Seven_1Low.mp3',
    u'Music\\DNGN\\Dungeon7\\mus_DNGN_Seven_2Mid.mp3',
    u'Music\\DNGN\\Dungeon7\\mus_DNGN_Seven_3High.mp3',
    u'Music\\DNGN\\Dungeon8\\mus_DNGN_Eight_1Low.mp3',
    u'Music\\DNGN\\Dungeon8\\mus_DNGN_Eight_2Mid.mp3',
    u'Music\\DNGN\\Dungeon8\\mus_DNGN_Eight_3High.mp3',
    u'Music\\Fallout1and2\\Fallout\\01MetallicMonks.mp3',
    u'Music\\Fallout1and2\\Fallout\\02DesertWind.mp3',
    u'Music\\Fallout1and2\\Fallout\\03ATradersLife.mp3',
    u'Music\\Fallout1and2\\Fallout\\04TheVaultoftheFuture.mp3',
    u'Music\\Fallout1and2\\Fallout\\05IndustrialJunk.mp3',
    u'Music\\Fallout1and2\\Fallout\\06MoribundWorld.mp3',
    u'Music\\Fallout1and2\\Fallout\\07VatsofGoo.mp3',
    u'Music\\Fallout1and2\\Fallout\\08CityoftheDead.mp3',
    u'Music\\Fallout1and2\\Fallout\\09SecondChance.mp3',
    u'Music\\Fallout1and2\\Fallout\\10UndergroundTroubles.mp3',
    u'Music\\Fallout1and2\\Fallout\\11CityofLostAngels.mp3',
    u'Music\\Fallout1and2\\Fallout\\12FollowersCredo.mp3',
    u'Music\\Fallout1and2\\Fallout\\13RadiationStorm.mp3',
    u'Music\\Fallout1and2\\Fallout\\14AcolytesoftheNewgod.mp3',
    u'Music\\Fallout1and2\\Fallout\\15FlameoftheAncientWorld.mp3',
    u'Music\\Fallout1and2\\Fallout\\16KhansofNewCalifornia.mp3',
    u'Music\\Fallout1and2\\Fallout2\\Arroyo.mp3',
    u'Music\\Fallout1and2\\Fallout2\\Modoc.mp3',
    u'Music\\Fallout1and2\\Fallout2\\NewReno.mp3',
    u'Music\\Fallout1and2\\Fallout2\\Redding.mp3',
    u'Music\\Fallout1and2\\Fallout2\\SanFrancisco.mp3',
    u'Music\\Fallout1and2\\Fallout2\\VaultCity.mp3',
    u'Music\\Fallout1and2\\Fallout2\\Worldmap1.mp3',
    u'Music\\Fallout1and2\\Fallout2\\Worldmap2.mp3',
    u'Music\\LOC\\CaesarsLegion\\mus_LOC_Caesar_Day_1Low.mp3',
    u'Music\\LOC\\CaesarsLegion\\mus_LOC_Caesar_Day_2Mid.mp3',
    u'Music\\LOC\\CaesarsLegion\\mus_LOC_Caesar_Day_3High.mp3',
    u'Music\\LOC\\CaesarsLegion\\mus_LOC_Caesar_Night_1Low.mp3',
    u'Music\\LOC\\CaesarsLegion\\mus_LOC_Caesar_Night_2Mid.mp3',
    u'Music\\LOC\\CaesarsLegion\\mus_LOC_Caesar_Night_3High.mp3',
    u'Music\\LOC\\CorporateRuins\\mus_LOC_CorpRuins_Day_1Low.mp3',
    u'Music\\LOC\\CorporateRuins\\mus_LOC_CorpRuins_Day_2Mid.mp3',
    u'Music\\LOC\\CorporateRuins\\mus_LOC_CorpRuins_Day_3High.mp3',
    u'Music\\LOC\\CorporateRuins\\mus_LOC_CorpRuins_Night_1Low.mp3',
    u'Music\\LOC\\CorporateRuins\\mus_LOC_CorpRuins_Night_2Mid.mp3',
    u'Music\\LOC\\CorporateRuins\\mus_LOC_CorpRuins_Night_3High.mp3',
    u'Music\\LOC\\DesertExploration\\mus_LOC_DesExpl_Day_1Low.mp3',
    u'Music\\LOC\\DesertExploration\\mus_LOC_DesExpl_Day_2Mid.mp3',
    u'Music\\LOC\\DesertExploration\\mus_LOC_DesExpl_Day_3High.mp3',
    u'Music\\LOC\\DesertExploration\\mus_LOC_DesExpl_Night_1Low.mp3',
    u'Music\\LOC\\DesertExploration\\mus_LOC_DesExpl_Night_2Mid.mp3',
    u'Music\\LOC\\DesertExploration\\mus_LOC_DesExpl_Night_3High.mp3',
    u'Music\\LOC\\DesertSettlement\\mus_LOC_DesSttl_Day_1Low.mp3',
    u'Music\\LOC\\DesertSettlement\\mus_LOC_DesSttl_Day_2Mid.mp3',
    u'Music\\LOC\\DesertSettlement\\mus_LOC_DesSttl_Day_3High.mp3',
    u'Music\\LOC\\DesertSettlement\\mus_LOC_DesSttl_Night_1Low.mp3',
    u'Music\\LOC\\DesertSettlement\\mus_LOC_DesSttl_Night_2Mid.mp3',
    u'Music\\LOC\\DesertSettlement\\mus_LOC_DesSttl_Night_3High.mp3',
    u'Music\\LOC\\Freeside\\mus_LOC_Freeside_Day_1Low.mp3',
    u'Music\\LOC\\Freeside\\mus_LOC_Freeside_Day_2Mid.mp3',
    u'Music\\LOC\\Freeside\\mus_LOC_Freeside_Day_3High.mp3',
    u'Music\\LOC\\Freeside\\mus_LOC_Freeside_Night_1Low.mp3',
    u'Music\\LOC\\Freeside\\mus_LOC_Freeside_Night_2Mid.mp3',
    u'Music\\LOC\\Freeside\\mus_LOC_Freeside_Night_3High.mp3',
    u'Music\\LOC\\HooverDam\\mus_LOC_Hoover_Caesar_1Low.mp3',
    u'Music\\LOC\\HooverDam\\mus_LOC_Hoover_Caesar_2Mid.mp3',
    u'Music\\LOC\\HooverDam\\mus_LOC_Hoover_Caesar_3High.mp3',
    u'Music\\LOC\\HooverDam\\mus_LOC_Hoover_NCR_1Low.mp3',
    u'Music\\LOC\\HooverDam\\mus_LOC_Hoover_NCR_2Mid.mp3',
    u'Music\\LOC\\HooverDam\\mus_LOC_Hoover_NCR_3High.mp3',
    u'Music\\LOC\\IndustrialCity\\mus_LOC_Industrial_Day_1Low.mp3',
    u'Music\\LOC\\IndustrialCity\\mus_LOC_Industrial_Day_2Mid.mp3',
    u'Music\\LOC\\IndustrialCity\\mus_LOC_Industrial_Day_3High(alt1).mp3',
    u'Music\\LOC\\IndustrialCity\\mus_LOC_Industrial_Day_3High.mp3',
    u'Music\\LOC\\IndustrialCity\\mus_LOC_Industrial_Night_1Low.mp3',
    u'Music\\LOC\\IndustrialCity\\mus_LOC_Industrial_Night_2Mid.mp3',
    u'Music\\LOC\\IndustrialCity\\mus_LOC_Industrial_Night_3High(alt1).mp3',
    u'Music\\LOC\\IndustrialCity\\mus_LOC_Industrial_Night_3High.mp3',
    u'Music\\LOC\\Jacobstown\\mus_LOC_Jacobstown_Day_1Low.mp3',
    u'Music\\LOC\\Jacobstown\\mus_LOC_Jacobstown_Day_2Mid.mp3',
    u'Music\\LOC\\Jacobstown\\mus_LOC_Jacobstown_Day_3High.mp3',
    u'Music\\LOC\\Jacobstown\\mus_LOC_Jacobstown_Night_1Low.mp3',
    u'Music\\LOC\\Jacobstown\\mus_LOC_Jacobstown_Night_2Mid.mp3',
    u'Music\\LOC\\Jacobstown\\mus_LOC_Jacobstown_Night_3High.mp3',
    u'Music\\LOC\\LargerTown\\mus_LOC_LrgTown_Day_1Low.mp3',
    u'Music\\LOC\\LargerTown\\mus_LOC_LrgTown_Day_2Mid.mp3',
    u'Music\\LOC\\LargerTown\\mus_LOC_LrgTown_Day_3High(alt1).mp3',
    u'Music\\LOC\\LargerTown\\mus_LOC_LrgTown_Day_3High.mp3',
    u'Music\\LOC\\LargerTown\\mus_LOC_LrgTown_Night_1Low.mp3',
    u'Music\\LOC\\LargerTown\\mus_LOC_LrgTown_Night_2Mid.mp3',
    u'Music\\LOC\\LargerTown\\mus_LOC_LrgTown_Night_3High.mp3',
    u'Music\\LOC\\Mountain\\mus_LOC_Mountain_Day_1Low.mp3',
    u'Music\\LOC\\Mountain\\mus_LOC_Mountain_Day_2Mid.mp3',
    u'Music\\LOC\\Mountain\\mus_LOC_Mountain_Day_3High.mp3',
    u'Music\\LOC\\Mountain\\mus_LOC_Mountain_Night_1Low.mp3',
    u'Music\\LOC\\Mountain\\mus_LOC_Mountain_Night_2Mid.mp3',
    u'Music\\LOC\\Mountain\\mus_LOC_Mountain_Night_3High.mp3',
    u'Music\\LOC\\NewCaliforniaRepublic\\mus_LOC_CalRepublic_Day_1Low.mp3',
    u'Music\\LOC\\NewCaliforniaRepublic\\mus_LOC_CalRepublic_Day_2Mid.mp3',
    u'Music\\LOC\\NewCaliforniaRepublic\\mus_LOC_CalRepublic_Day_3High.mp3',
    u'Music\\LOC\\NewCaliforniaRepublic\\mus_LOC_CalRepublic_Night_1Low.mp3',
    u'Music\\LOC\\NewCaliforniaRepublic\\mus_LOC_CalRepublic_Night_2Mid.mp3',
    u'Music\\LOC\\NewCaliforniaRepublic\\mus_LOC_CalRepublic_Night_3High.mp3',
    u'Music\\OLD\\FO1\\mus_FO1_AcolytesOfTheNewGod.mp3',
    u'Music\\OLD\\FO1\\mus_FO1_CityOfLostAngels.mp3',
    u'Music\\OLD\\FO1\\mus_FO1_CityOfTheDead.mp3',
    u'Music\\OLD\\FO1\\mus_FO1_DesertWind.mp3',
    u'Music\\OLD\\FO1\\mus_FO1_FlameOfTheAncientWorld.mp3',
    u'Music\\OLD\\FO1\\mus_FO1_IndustrialJunk.mp3',
    u'Music\\OLD\\FO1\\mus_FO1_MetallicMonks.mp3',
    u'Music\\OLD\\FO1\\mus_FO1_RadiationStorm.mp3',
    u'Music\\OLD\\FO1\\mus_FO1_SecondChance.mp3',
    u'Music\\OLD\\FO1\\mus_FO1_TheVaultOfTheFuture.mp3',
    u'Music\\OLD\\FO1\\mus_FO1_UndergroundTrouble.mp3',
    u'Music\\OLD\\FO2\\mus_FO2_Modoc.mp3',
    u'Music\\OLD\\FO2\\mus_FO2_Redding.mp3',
    u'Music\\OLD\\FO3\\mus_FO3_Base2.mp3',
    u'Music\\OLD\\FO3\\mus_FO3_Base3.mp3',
    u'Music\\OLD\\FO3\\mus_FO3_Base5.mp3',
    u'Music\\OLD\\FO3\\mus_FO3_Death.mp3',
    u'Music\\OLD\\FO3\\mus_FO3_Dungeon1.mp3',
    u'Music\\OLD\\FO3\\mus_FO3_Dungeon2.mp3',
    u'Music\\OLD\\FO3\\mus_FO3_Dungeon3.mp3',
    u'Music\\OLD\\FO3\\mus_FO3_Explore1.mp3',
    u'Music\\OLD\\FO3\\mus_FO3_Explore3.mp3',
    u'Music\\OLD\\FO3\\mus_FO3_Explore4.mp3',
    u'Music\\OLD\\FO3\\mus_FO3_Explore5.mp3',
    u'Music\\OLD\\FO3\\mus_FO3_Explore6.mp3',
    u'Music\\SCR\\mus_SCR_DeathStinger.mp3',
    u'Music\\SCR\\mus_SCR_DocMitchell.mp3',
    u'Music\\SCR\\mus_SCR_GoodspringsStinger.mp3',
    u'Music\\SCR\\mus_SCR_Muzak.mp3',
    u'Music\\SCR\\mus_SCR_MuzakRadio.mp3',
    u'Music\\SCR\\mus_SCR_VegasStinger.mp3',
    u'Music\\SCR\\mus_SCR_VictorySinger(alt1).mp3',
    u'Music\\SCR\\mus_SCR_VictorySinger(alt2).mp3',
    u'Music\\SCR\\mus_SCR_VictorySinger.mp3',
    u'Music\\Special\\EndCredits.mp3',
    u'Music\\Special\\MainTitle.mp3',
    u'Music\\Special\\mus_endgameslideshow.mp3',
    u'Music\\Special\\mus_endgametransitionstinger.mp3',
    u'Music\\Special\\mus_hailchief.mp3',
    u'Shaders\\shaderpackage002.sdp',
    u'Shaders\\shaderpackage003.sdp',
    u'Shaders\\shaderpackage004.sdp',
    u'Shaders\\shaderpackage006.sdp',
    u'Shaders\\shaderpackage007.sdp',
    u'Shaders\\shaderpackage009.sdp',
    u'Shaders\\shaderpackage010.sdp',
    u'Shaders\\shaderpackage011.sdp',
    u'Shaders\\shaderpackage012.sdp',
    u'Shaders\\shaderpackage013.sdp',
    u'Shaders\\shaderpackage014.sdp',
    u'Shaders\\shaderpackage015.sdp',
    u'Shaders\\shaderpackage016.sdp',
    u'Shaders\\shaderpackage017.sdp',
    u'Shaders\\shaderpackage018.sdp',
    u'Shaders\\shaderpackage019.sdp',
    u'Sound\\songs\\radionv\\MUS_Aint_That_A_Kick_In_the_Head.mp3',
    u'Sound\\songs\\radionv\\MUS_American_Swing.mp3',
    u'Sound\\songs\\radionv\\MUS_Big_Iron.mp3',
    u'Sound\\songs\\radionv\\MUS_Blues_For_You.mp3',
    u'Sound\\songs\\radionv\\MUS_Blue_Moon.mp3',
    u'Sound\\songs\\radionv\\MUS_Cobwebs_and_Rainbows.mp3',
    u'Sound\\songs\\radionv\\MUS_Concerto_For_2_Vl_Str_In_D_Minor.mp3',
    u'Sound\\songs\\radionv\\MUS_Concerto_Grosso_In_B_Minor_Allegro_01.mp3',
    u'Sound\\songs\\radionv\\MUS_Concerto_Grosso_In_B_Minor_Allegro_02.mp3',
    u'Sound\\songs\\radionv\\MUS_EddyArnold_Rca_ItsASin.mp3',
    u'Sound\\songs\\radionv\\MUS_Flower_Duet_Lakm_KPM.mp3',
    u'Sound\\songs\\radionv\\MUS_Four_Seasons_No_4_The_Winter.mp3',
    u'Sound\\songs\\radionv\\MUS_Goin_Under.mp3',
    u'Sound\\songs\\radionv\\MUS_Hallo_Mister_X.mp3',
    u'Sound\\songs\\radionv\\MUS_Happy_Times.mp3',
    u'Sound\\songs\\radionv\\MUS_Heartaches_by_the_Number.mp3',
    u'Sound\\songs\\radionv\\MUS_HomeOnTheWastes.mp3',
    u'Sound\\songs\\radionv\\MUS_In_The_Shadow_Of_The_Valley.mp3',
    u'Sound\\songs\\radionv\\MUS_Its_A_Sin_To_Tell_A_Lie.mp3',
    u'Sound\\songs\\radionv\\MUS_I_m_Movin_Out.mp3',
    u'Sound\\songs\\radionv\\MUS_I_m_So_Blue.mp3',
    u'Sound\\songs\\radionv\\MUS_Jazz_Blues_GT.mp3',
    u'Sound\\songs\\radionv\\MUS_Jazz_Club_Blues_CAS.mp3',
    u'Sound\\songs\\radionv\\MUS_Jingle_Jangle_Jingle.mp3',
    u'Sound\\songs\\radionv\\MUS_Joe_Cool_CAS.mp3',
    u'Sound\\songs\\radionv\\MUS_Johnny_Guitar.mp3',
    u'Sound\\songs\\radionv\\MUS_Lazy_Day_Blues.mp3',
    u'Sound\\songs\\radionv\\MUS_Let_s_Ride_Into_The_Sunset_Together.mp3',
    u'Sound\\songs\\radionv\\MUS_Lone_Star.mp3',
    u'Sound\\songs\\radionv\\MUS_Love_Me_As_Though_No_Tomorrow.mp3',
    u'Sound\\songs\\radionv\\MUS_Mad_About_The_Boy.mp3',
    u'Sound\\songs\\radionv\\MUS_Manhattan.mp3',
    u'Sound\\songs\\radionv\\MUS_NewVegasValley.mp3',
    u'Sound\\songs\\radionv\\MUS_Piano_Concerto_No_21__Elvira_Madigan.mp3',
    u'Sound\\songs\\radionv\\MUS_Ride_Of_The_Valkyries_01.mp3',
    u'Sound\\songs\\radionv\\MUS_Roundhouse_Rock.mp3',
    u'Sound\\songs\\radionv\\MUS_Sit_And_Dream.mp3',
    u'Sound\\songs\\radionv\\MUS_Sleepy_Town_Blues_CAS.mp3',
    u'Sound\\songs\\radionv\\MUS_Slow_Bounce.mp3',
    u'Sound\\songs\\radionv\\MUS_Slow_Sax_KOS.mp3',
    u'Sound\\songs\\radionv\\MUS_Somethings_Gotta_Give.mp3',
    u'Sound\\songs\\radionv\\MUS_Spring_Song_KPMC.mp3',
    u'Sound\\songs\\radionv\\MUS_Stars_Of_The_Midnight_Range.mp3',
    u'Sound\\songs\\radionv\\MUS_Strahlende_Trompete.mp3',
    u'Sound\\songs\\radionv\\MUS_StreetsOfNewReno.mp3',
    u'Sound\\songs\\radionv\\MUS_Von_Spanien_Nach_S_damerika.mp3',
    u'Sound\\songs\\radionv\\MUS_Where_Have_You_Been_All_My_Life.mp3',
    u'Sound\\songs\\radionv\\MUS_Why_Dont_You_Do_Right.mp3',
    u'Video\\FNVIntro.bik',
    # Section 2: Preorder Packs
    u'CaravanPack - Main.bsa',
    u'CaravanPack.esm',
    u'CaravanPack.nam',
    u'ClassicPack - Main.bsa',
    u'ClassicPack.esm',
    u'ClassicPack.nam',
    u'MercenaryPack - Main.bsa',
    u'MercenaryPack.esm',
    u'MercenaryPack.nam',
    u'TribalPack - Main.bsa',
    u'TribalPack.esm',
    u'TribalPack.nam',
    # Section 3: DLCs
    u'DEADMONEY.NAM',
    u'DeadMoney - Main.bsa',
    u'DeadMoney - Sounds.bsa',
    u'DeadMoney.esm',
    u'GUNRUNNERSARSENAL.NAM',
    u'GunRunnersArsenal - Main.bsa',
    u'GunRunnersArsenal - Sounds.bsa',
    u'GunRunnersArsenal.esm',
    u'HONESTHEARTS.NAM',
    u'HonestHearts - Main.bsa',
    u'HonestHearts - Sounds.bsa',
    u'HonestHearts.esm',
    u'LONESOMEROAD.NAM',
    u'LonesomeRoad - Main.bsa',
    u'LonesomeRoad - Sounds.bsa',
    u'LonesomeRoad.esm',
    u'OLDWORLDBLUES.NAM',
    u'OldWorldBlues - Main.bsa',
    u'OldWorldBlues - Sounds.bsa',
    u'OldWorldBlues.esm',
    u'DLCList.txt',
}
