# -*- coding: utf-8 -*-
#
# GPL License and Copyright Notice ============================================
#  This file is part of Wrye Bash.
#
#  Wrye Bash is free software: you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation, either version 3
#  of the License, or (at your option) any later version.
#
#  Wrye Bash is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Wrye Bash.  If not, see <https://www.gnu.org/licenses/>.
#
#  Wrye Bash copyright (C) 2005-2009 Wrye, 2010-2021 Wrye Bash Team
#  https://github.com/wrye-bash
#
# =============================================================================
"""This module lists the files installed in the Data folder in a completely
vanilla Fallout 4 setup."""

# Generated with:
#  find . -type f | cut -d'/' -f 2- | sed -e "s/^/'/; s/$/',/; s./.\\\\\\\.g"
# Then manually added entries for other languages from SteamDB:
# https://steamdb.info/app/377160/depots/
vanilla_files = {
    u'ccBGSFO4001-PipBoy(Black) - Main.ba2',
    u'ccBGSFO4001-PipBoy(Black) - Textures.ba2',
    u'ccBGSFO4003-PipBoy(Camo01) - Main.ba2',
    u'ccBGSFO4003-PipBoy(Camo01) - Textures.ba2',
    u'ccBGSFO4004-PipBoy(Camo02) - Main.ba2',
    u'ccBGSFO4004-PipBoy(Camo02) - Textures.ba2',
    u'ccBGSFO4006-PipBoy(Chrome) - Main.ba2',
    u'ccBGSFO4006-PipBoy(Chrome) - Textures.ba2',
    u'ccBGSFO4016-Prey - Main.ba2',
    u'ccBGSFO4016-Prey - Textures.ba2',
    u'ccBGSFO4018-GaussRiflePrototype - Main.ba2',
    u'ccBGSFO4018-GaussRiflePrototype - Textures.ba2',
    u'ccBGSFO4019-ChineseStealthArmor - Main.ba2',
    u'ccBGSFO4019-ChineseStealthArmor - Textures.ba2',
    u'ccBGSFO4020-PowerArmorSkin(Black) - Main.ba2',
    u'ccBGSFO4020-PowerArmorSkin(Black) - Textures.ba2',
    u'ccBGSFO4038-HorseArmor - Main.ba2',
    u'ccBGSFO4038-HorseArmor - Textures.ba2',
    u'ccBGSFO4044-HellfirePowerArmor - Main.ba2',
    u'ccBGSFO4044-HellfirePowerArmor - Textures.ba2',
    u'ccFRSFO4001-HandmadeShotgun - Main.ba2',
    u'ccFRSFO4001-HandmadeShotgun - Textures.ba2',
    u'ccFSVFO4001-ModularMilitaryBackpack - Main.ba2',
    u'ccFSVFO4001-ModularMilitaryBackpack - Textures.ba2',
    u'ccFSVFO4002-MidCenturyModern - Main.ba2',
    u'ccFSVFO4002-MidCenturyModern - Textures.ba2',
    u'DLCCoast - Geometry.csg',
    u'DLCCoast - Main.ba2',
    u'DLCCoast - Textures.ba2',
    u'DLCCoast - Voices_de.ba2',
    u'DLCCoast - Voices_en.ba2',
    u'DLCCoast - Voices_es.ba2',
    u'DLCCoast - Voices_fr.ba2',
    u'DLCCoast - Voices_it.ba2',
    u'DLCCoast - Voices_ja.ba2',
    u'DLCCoast.cdx',
    u'DLCCoast.esm',
    u'DLCNukaWorld - Geometry.csg',
    u'DLCNukaWorld - Main.ba2',
    u'DLCNukaWorld - Textures.ba2',
    u'DLCNukaWorld - Voices_de.ba2',
    u'DLCNukaWorld - Voices_en.ba2',
    u'DLCNukaWorld - Voices_es.ba2',
    u'DLCNukaWorld - Voices_fr.ba2',
    u'DLCNukaWorld - Voices_it.ba2',
    u'DLCNukaWorld - Voices_ja.ba2',
    u'DLCNukaWorld.cdx',
    u'DLCNukaWorld.esm',
    u'DLCRobot - Geometry.csg',
    u'DLCRobot - Main.ba2',
    u'DLCRobot - Textures.ba2',
    u'DLCRobot - Voices_de.ba2',
    u'DLCRobot - Voices_en.ba2',
    u'DLCRobot - Voices_es.ba2',
    u'DLCRobot - Voices_fr.ba2',
    u'DLCRobot - Voices_it.ba2',
    u'DLCRobot - Voices_ja.ba2',
    u'DLCRobot.cdx',
    u'DLCRobot.esm',
    u'DLCworkshop01 - Geometry.csg',
    u'DLCworkshop01 - Main.ba2',
    u'DLCworkshop01 - Textures.ba2',
    u'DLCworkshop01.cdx',
    u'DLCworkshop01.esm',
    u'DLCworkshop02 - Main.ba2',
    u'DLCworkshop02 - Textures.ba2',
    u'DLCworkshop02.esm',
    u'DLCworkshop03 - Geometry.csg',
    u'DLCworkshop03 - Main.ba2',
    u'DLCworkshop03 - Textures.ba2',
    u'DLCworkshop03 - Voices_de.ba2',
    u'DLCworkshop03 - Voices_en.ba2',
    u'DLCworkshop03 - Voices_es.ba2',
    u'DLCworkshop03 - Voices_fr.ba2',
    u'DLCworkshop03 - Voices_it.ba2',
    u'DLCworkshop03 - Voices_ja.ba2',
    u'DLCworkshop03.cdx',
    u'DLCworkshop03.esm',
    u'Fallout4 - Animations.ba2',
    u'Fallout4 - Geometry.csg',
    u'Fallout4 - Interface.ba2',
    u'Fallout4 - Materials.ba2',
    u'Fallout4 - Meshes.ba2',
    u'Fallout4 - MeshesExtra.ba2',
    u'Fallout4 - Misc.ba2',
    u'Fallout4 - Nvflex.ba2',
    u'Fallout4 - Shaders.ba2',
    u'Fallout4 - Sounds.ba2',
    u'Fallout4 - Startup.ba2',
    u'Fallout4 - Textures1.ba2',
    u'Fallout4 - Textures2.ba2',
    u'Fallout4 - Textures3.ba2',
    u'Fallout4 - Textures4.ba2',
    u'Fallout4 - Textures5.ba2',
    u'Fallout4 - Textures6.ba2',
    u'Fallout4 - Textures7.ba2',
    u'Fallout4 - Textures8.ba2',
    u'Fallout4 - Textures9.ba2',
    u'Fallout4 - Voices.ba2',
    u'Fallout4 - Voices_de.ba2',
    u'Fallout4 - Voices_es.ba2',
    u'Fallout4 - Voices_fr.ba2',
    u'Fallout4 - Voices_it.ba2',
    u'Fallout4 - Voices_rep.ba2',
    u'Fallout4.cdx',
    u'Fallout4.esm',
    u'LSData\\DtC6dal.dat',
    u'LSData\\DtC6dl.dat',
    u'LSData\\Wt16M9bs.dat',
    u'LSData\\Wt16M9fs.dat',
    u'LSData\\Wt8S9bs.dat',
    u'LSData\\Wt8S9fs.dat',
    u'Scripts\\Source\\Base\\Base.zip',
    u'Scripts\\Source\\CreationClub\\CreationClub.zip',
    u'Scripts\\Source\\DLC01\\DLC01.zip',
    u'Scripts\\Source\\DLC02\\DLC02.zip',
    u'Scripts\\Source\\DLC03\\DLC03.zip',
    u'Scripts\\Source\\DLC04\\DLC04.zip',
    u'Scripts\\Source\\DLC05\\DLC05.zip',
    u'Scripts\\Source\\DLC06\\DLC06.zip',
    u'Scripts\\Source\\User\\Readme.txt',
    u'Sound\\Voice\\Processing\\FonixData.cdf',
    u'Video\\AGILITY.bk2',
    u'Video\\CHARISMA.bk2',
    u'Video\\Endgame_FEMALE_A.bk2',
    u'Video\\Endgame_FEMALE_A_PTBR.bk2',
    u'Video\\Endgame_FEMALE_A_PL.bk2',
    u'Video\\Endgame_FEMALE_A_RU.bk2',
    u'Video\\Endgame_FEMALE_B.bk2',
    u'Video\\Endgame_FEMALE_B_PL.bk2',
    u'Video\\Endgame_FEMALE_B_PTBR.bk2',
    u'Video\\Endgame_FEMALE_B_RU.bk2',
    u'Video\\Endgame_MALE_A.bk2',
    u'Video\\Endgame_MALE_A_PL.bk2',
    u'Video\\Endgame_MALE_A_PTBR.bk2',
    u'Video\\Endgame_MALE_A_RU.bk2',
    u'Video\\Endgame_MALE_B.bk2',
    u'Video\\Endgame_MALE_B_PL.bk2',
    u'Video\\Endgame_MALE_B_PTBR.bk2',
    u'Video\\Endgame_MALE_B_RU.bk2',
    u'Video\\ENDURANCE.bk2',
    u'Video\\GameIntro_V3_B.bk2',
    u'Video\\INTELLIGENCE.bk2',
    u'Video\\Intro.bk2',
    u'Video\\Intro_pl.bk2',
    u'Video\\Intro_ptbr.bk2',
    u'Video\\Intro_ru.bk2',
    u'Video\\LUCK.bk2',
    u'Video\\MainMenuLoop.bk2',
    u'Video\\PERCEPTION.bk2',
    u'Video\\STRENGTH.bk2',
}
