# -*- coding: utf-8 -*-
#
# GPL License and Copyright Notice ============================================
#  This file is part of Wrye Bash.
#
#  Wrye Bash is free software: you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation, either version 3
#  of the License, or (at your option) any later version.
#
#  Wrye Bash is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Wrye Bash.  If not, see <https://www.gnu.org/licenses/>.
#
#  Wrye Bash copyright (C) 2005-2009 Wrye, 2010-2021 Wrye Bash Team
#  https://github.com/wrye-bash
#
# =============================================================================
"""This module lists the files installed in the Data folder in a completely
vanilla Nehrim setup."""

# Generated with:
#  find . -type f | cut -d'/' -f 2- | sed -e "s/^/'/; s/$/',/; s./.\\\\\\\.g"
vanilla_files = {
    u'Credits.txt',
    u'L - Misc.bsa',
    u'L - Voices.bsa',
    u'Music\\Battle\\Battle_01.mp3',
    u'Music\\Battle\\Battle_02.mp3',
    u'Music\\Battle\\Battle_03.mp3',
    u'Music\\Battle\\Battle_04.mp3',
    u'Music\\Battle\\Battle_05.mp3',
    u'Music\\Battle\\Battle_06.mp3',
    u'Music\\Battle\\Battle_07.mp3',
    u'Music\\Battle\\Battle_08.mp3',
    u'Music\\Battle\\Battle_09.mp3',
    u'Music\\Battle\\Battle_10.mp3',
    u'Music\\Battle\\Battle_11.mp3',
    u'Music\\Dungeon\\Dungeon_01.mp3',
    u'Music\\Dungeon\\Dungeon_02.mp3',
    u'Music\\Dungeon\\Dungeon_03.mp3',
    u'Music\\Dungeon\\Dungeon_04.mp3',
    u'Music\\Dungeon\\Dungeon_05.mp3',
    u'Music\\Dungeon\\Dungeon_06.mp3',
    u'Music\\Dungeon\\Dungeon_07.mp3',
    u'Music\\Dungeon\\Dungeon_08.mp3',
    u'Music\\Dungeon\\Dungeon_09.mp3',
    u'Music\\Dungeon\\Dungeon_10.mp3',
    u'Music\\Dungeon\\Dungeon_11.mp3',
    u'Music\\Explore\\Atmosphere_01.mp3',
    u'Music\\Explore\\Atmosphere_02.mp3',
    u'Music\\Explore\\Atmosphere_03.mp3',
    u'Music\\Explore\\Atmosphere_04.mp3',
    u'Music\\Explore\\Atmosphere_05.mp3',
    u'Music\\Explore\\Atmosphere_06.mp3',
    u'Music\\Explore\\Atmosphere_07.mp3',
    u'Music\\Explore\\Atmosphere_08.mp3',
    u'Music\\Explore\\Atmosphere_09.mp3',
    u'Music\\Explore\\Atmosphere_10.mp3',
    u'Music\\Explore\\Atmosphere_11.mp3',
    u'Music\\Explore\\Atmosphere_12.mp3',
    u'Music\\Explore\\Atmosphere_13.mp3',
    u'Music\\Explore\\Atmosphere_14.mp3',
    u'Music\\Explore\\Atmosphere_15.mp3',
    u'Music\\Explore\\Atmosphere_16.mp3',
    u'Music\\Public\\Town_01.mp3',
    u'Music\\Public\\Town_02.mp3',
    u'Music\\Public\\Town_03.mp3',
    u'Music\\Public\\Town_04.mp3',
    u'Music\\Public\\Town_05.mp3',
    u'Music\\Public\\Town_06.mp3',
    u'Music\\Public\\Town_07.mp3',
    u'Music\\Public\\Town_08.mp3',
    u'Music\\Special\\death.mp3',
    u'Music\\Special\\Event_01.mp3',
    u'Music\\Special\\Event_02.mp3',
    u'Music\\Special\\Event_03.mp3',
    u'Music\\Special\\Event_04.mp3',
    u'Music\\Special\\Event_05.mp3',
    u'Music\\Special\\Event_06.mp3',
    u'Music\\Special\\Event_08.mp3',
    u'Music\\Special\\GodShrineAmbient.mp3',
    u'Music\\Special\\Nehrim_Expansion_Event01.mp3',
    u'Music\\Special\\Nehrim_Expansion_Event02.mp3',
    u'Music\\Special\\Nehrim_Expansion_Special01.mp3',
    u'Music\\Special\\Nehrim_Expansion_Special02.mp3',
    u'Music\\Special\\Sanctum_Ambient01.mp3',
    u'Music\\Special\\Sanctum_Sequence01.mp3',
    u'Music\\Special\\Sanctum_Sequence02.mp3',
    u'Music\\Special\\Silence.mp3',
    u'Music\\Special\\success.mp3',
    u'Music\\Special\\Tes4title.mp3',
    u'Music\\Special\\Theme_01.mp3',
    u'Music\\Special\\Theme_02.mp3',
    u'Music\\Special\\Theme_03.mp3',
    u'Music\\Special\\Theme_04.mp3',
    u'Music\\Special\\Theme_05.mp3',
    u'Music\\Special\\Theme_06.mp3',
    u'Music\\Special\\Theme_06a.mp3',
    u'Music\\Special\\Theme_07.mp3',
    u'Music\\Special\\Theme_08.mp3',
    u'Music\\Special\\Theme_09.mp3',
    u'Music\\Special\\Theme_10.mp3',
    u'N - Meshes.bsa',
    u'N - Misc.bsa',
    u'N - Sounds.bsa',
    u'N - Textures1.bsa',
    u'N - Textures2.bsa',
    u'Nehrim.esm',
    u'OBSE\\obse.ini',
    u'OBSE\\plugins\\AltTabFix.dll',
    u'OBSE\\plugins\\Blockhead.dll',
    u'OBSE\\plugins\\Blockhead.ini',
    u'OBSE\\plugins\\EnhancedMusicControl 2.dll',
    u'OBSE\\plugins\\EnhancedMusicControl 2.ini',
    u'OBSE\\plugins\\nehrim_steam.dll',
    u'OBSE\\plugins\\WalkBlessed.dll',
    u'OBSE\\plugins\\WalkBlessed.ini',
    u'OBSE\\plugins\\WalkBlessed.log',
    u'Shaders\\shaderpackage001.sdp',
    u'Shaders\\shaderpackage002.sdp',
    u'Shaders\\shaderpackage003.sdp',
    u'Shaders\\shaderpackage004.sdp',
    u'Shaders\\shaderpackage005.sdp',
    u'Shaders\\shaderpackage006.sdp',
    u'Shaders\\shaderpackage007.sdp',
    u'Shaders\\shaderpackage008.sdp',
    u'Shaders\\shaderpackage009.sdp',
    u'Shaders\\shaderpackage010.sdp',
    u'Shaders\\shaderpackage011.sdp',
    u'Shaders\\shaderpackage012.sdp',
    u'Shaders\\shaderpackage013.sdp',
    u'Shaders\\shaderpackage014.sdp',
    u'Shaders\\shaderpackage015.sdp',
    u'Shaders\\shaderpackage016.sdp',
    u'Shaders\\shaderpackage017.sdp',
    u'Shaders\\shaderpackage018.sdp',
    u'Shaders\\shaderpackage019.sdp',
    u'Translation.esp',
    u'Video\\KimFPalaSzene.bik',
    u'Video\\KimMPalaSzene.bik',
    u'Video\\map loop.bik',
    u'Video\\Nehrim Outro.bik',
    u'Video\\Oblivion iv logo.bik',
    u'Video\\OblivionIntro.bik',
}
